/** Revalidates five failed v2 cases through strict no-model server grammar. */
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { config } from "dotenv";
import { createClient } from "@supabase/supabase-js";
import { chromium } from "playwright";
import type { Database } from "../../lib/types/database";
import type { WorkChatReply,WorkSnapshot } from "../../lib/jarvis/work-types";
config({path:[".env.eval.local",".env.local"],quiet:true});
type Case={id:string;kind:string;goal:string;progress:string;nextStep:string;message:string;taskTitle?:string};
const corpus=JSON.parse(readFileSync(new URL("../fixtures/work-context-browser-eval-v2.json",import.meta.url),"utf8")) as {cases:Case[]};const ids=["P03","P06","P08","P10","T05"],cases=ids.map(id=>corpus.cases.find(x=>x.id===id)!);
test("G7 five explicit v2 workflows pass deterministically with zero model calls",{timeout:90_000},async()=>{
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL!,app=process.env.G7_APP_URL??"http://localhost:3055";assert.equal(process.env.GATE_ISOLATED_DB,"1");assert.equal(url,"http://127.0.0.1:54721");assert.equal(cases.filter(Boolean).length,5);
 const db=createClient<Database>(url,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}});for(const table of ["work_contexts","tasks","dialogue_action_drafts"] as const){const r=await db.from(table).select("id",{count:"exact",head:true});assert.ifError(r.error);assert.equal(r.count,0);}
 const usage=await db.from("ai_usage").select("id",{count:"exact",head:true}).eq("purpose","dialogue");assert.ifError(usage.error);const callsBefore=usage.count??0;
 const link=await db.auth.admin.generateLink({type:"magiclink",email:process.env.ALLOWED_EMAIL!});assert.ifError(link.error);const owner=createClient(url,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{auth:{persistSession:false}}),login=await owner.auth.verifyOtp({type:"email",email:process.env.ALLOWED_EMAIL!,token:link.data.properties.email_otp});assert.ifError(login.error);
 const browser=await chromium.launch({channel:process.env.GATE_BROWSER_CHANNEL??"chrome",headless:true}),context=await browser.newContext();await context.addCookies([{name:"sb-127-auth-token",value:"base64-"+Buffer.from(JSON.stringify(login.data.session)).toString("base64url"),url:app}]);const contextIds:string[]=[],draftIds:string[]=[],approvalIds:string[]=[];
 const call=async<T>(path:string,data:unknown,method:"post"|"get"="post")=>{const r=await context.request[method](`${app}${path}`,{headers:{Origin:app},...(method==="post"?{data}: {})});const body=await r.json() as T;assert.equal(r.status(),200,JSON.stringify(body));return body;};
 try{
  for(const c of cases.filter(x=>x.kind==="preview")){const reply=await call<WorkChatReply>("/api/jarvis/work-chat",{messages:[{role:"user",content:c.message}],contextId:null,requestId:crypto.randomUUID()});assert.equal(reply.mode,"preview");assert.deepEqual(reply.preview,{goal:c.goal,progress:c.progress,nextStep:c.nextStep,deadlineAt:null,reminderAt:null,deadlineReminder:false,resumeReminder:false});const saved=await call<{work:WorkSnapshot}>("/api/jarvis/work-contexts",{requestId:crypto.randomUUID(),previewRequestId:reply.requestId,input:reply.preview});contextIds.push(saved.work.context.id);const restored=await call<{work:WorkSnapshot}>(`/api/jarvis/work-contexts/${saved.work.context.id}`,undefined,"get");assert.equal(restored.work.context.id,saved.work.context.id);assert.equal(restored.work.context.goal,c.goal);assert.equal(restored.work.context.progress,c.progress);assert.equal(restored.work.context.nextStep,c.nextStep);assert.equal(restored.work.context.revision,1);}
  const c=cases.find(x=>x.id==="T05")!,created=await call<{work:WorkSnapshot}>("/api/jarvis/work-contexts",{requestId:crypto.randomUUID(),input:{goal:c.goal,progress:c.progress,nextStep:c.nextStep,deadlineAt:null,reminderAt:null,deadlineReminder:false,resumeReminder:false}});contextIds.push(created.work.context.id);const proposed=await call<WorkChatReply>("/api/jarvis/work-chat",{messages:[{role:"user",content:c.message}],contextId:created.work.context.id,expectedRevision:1,requestId:crypto.randomUUID()});assert.equal(proposed.mode,"propose");const action=proposed.work!.actions.find(x=>x.draft.type==="CREATE_TASK");assert.ok(action);draftIds.push(action.draft.id);assert.equal((action.draft.payload as {title:string}).title,c.taskTitle);assert.equal((await db.from("tasks").select("id",{count:"exact",head:true})).count,0);const executed=await call<{work:WorkSnapshot}>(`/api/jarvis/work-contexts/${created.work.context.id}/actions/${action.id}`,{decision:"approved"});const done=executed.work.actions.find(x=>x.id===action.id)!;assert.equal(done.status,"executed");approvalIds.push(done.approvalId!);await call(`/api/jarvis/work-contexts/${created.work.context.id}/actions/${action.id}`,{decision:"approved"});const tasks=await db.from("tasks").select("id,title").eq("approval_request_id",done.approvalId!);assert.ifError(tasks.error);assert.deepEqual(tasks.data.map(x=>x.title),[c.taskTitle]);assert.equal(executed.work.context.status,"active");
  const after=await db.from("ai_usage").select("id",{count:"exact",head:true}).eq("purpose","dialogue");assert.ifError(after.error);assert.equal(after.count,callsBefore,"strict explicit grammar must make zero model calls");console.log(JSON.stringify({cases:5,passed:5,modelCalls:0,unauthorizedWrites:0,duplicateEffects:0,falseWholeWorkCompletion:0}));
 }finally{await browser.close();if(contextIds.length){const actions=await db.from("work_context_actions").select("draft_id").in("context_id",contextIds);assert.ifError(actions.error);draftIds.push(...actions.data!.map(x=>x.draft_id));const stamped=await db.from("dialogue_action_drafts").select("id,approval_request_id").in("source_snapshot->>workContextId",contextIds);assert.ifError(stamped.error);draftIds.push(...stamped.data!.map(x=>x.id));approvalIds.push(...stamped.data!.flatMap(x=>x.approval_request_id?[x.approval_request_id]:[]));const uniqueApprovals=[...new Set(approvalIds)],uniqueDrafts=[...new Set(draftIds)];if(uniqueApprovals.length){assert.ifError((await db.from("tasks").delete().in("approval_request_id",uniqueApprovals)).error);assert.ifError((await db.from("action_audit_logs").delete().in("approval_request_id",uniqueApprovals)).error);}assert.ifError((await db.from("work_context_actions").delete().in("context_id",contextIds)).error);assert.ifError((await db.from("work_context_requests").delete().in("context_id",contextIds)).error);if(uniqueDrafts.length)assert.ifError((await db.from("dialogue_action_drafts").delete().in("id",uniqueDrafts)).error);if(uniqueApprovals.length)assert.ifError((await db.from("approval_requests").delete().in("id",uniqueApprovals)).error);assert.ifError((await db.from("work_contexts").delete().in("id",contextIds)).error);}}
});
