import test from "node:test";
import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {config} from "dotenv";
import {createClient} from "@supabase/supabase-js";
import {chromium} from "playwright";
config({path:[".env.eval.local"],quiet:true});
const url=process.env.NEXT_PUBLIC_SUPABASE_URL!,app="http://localhost:3055",admin=createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}});
test("G8 voice mutation waits for screen confirmation and action approval executes once",{timeout:120000},async()=>{
  assert.equal(url,"http://127.0.0.1:54721");const link=await admin.auth.admin.generateLink({type:"magiclink",email:process.env.ALLOWED_EMAIL!});assert.ifError(link.error);const auth=createClient(url,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{auth:{persistSession:false}}),login=await auth.auth.verifyOtp({type:"email",email:process.env.ALLOWED_EMAIL!,token:link.data.properties.email_otp});assert.ifError(login.error);const owner=login.data.user!.id;
  const session=await admin.rpc("begin_voice_session",{p_owner_id:owner,p_mode:"push_to_talk",p_model:"gpt-live-transcribe",p_budget:5});assert.ifError(session.error);const sessionId=session.data.id;const browser=await chromium.launch({channel:"chrome",headless:true}),page=await browser.newPage();await page.context().addCookies([{name:"sb-127-auth-token",value:"base64-"+Buffer.from(JSON.stringify(login.data.session)).toString("base64url"),url:app}]);let contextId="",approvalId="",draftId="";
  const call=async(path:string,body:unknown)=>page.evaluate(async({path,body})=>{const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});return{status:r.status,data:await r.json()};},{path,body});
  try{await page.goto(`${app}/jarvis`);const created=await call("/api/jarvis/work-contexts",{requestId:randomUUID(),input:{goal:"음성 이력서 준비",progress:"초안 시작",nextStep:"성과 정리",deadlineAt:null,reminderAt:null,deadlineReminder:false,resumeReminder:false}});assert.equal(created.status,200,JSON.stringify(created.data));contextId=created.data.work.context.id;
    const updateRequest=randomUUID(),updateText='현재 진행은 “프로젝트 설명까지 했다”야. 다음 행동은 “성과 수치 정리”로 바꿔줘.';const update=await call("/api/jarvis/voice/turns",{sessionId,providerItemId:"voice-update",requestId:updateRequest,durationMs:1000,messages:[{role:"user",content:updateText}],contextId,expectedRevision:1});assert.equal(update.status,200,JSON.stringify(update.data));assert.ok(update.data.voice.confirmation);assert.equal(update.data.work.context.revision,1);const before=await auth.from("work_contexts").select("revision,progress,next_step").eq("id",contextId).single();assert.ifError(before.error);assert.equal(before.data.revision,1);assert.equal(before.data.progress,"초안 시작");
    const confirmed=await call("/api/jarvis/voice/confirm",update.data.voice.confirmation);assert.equal(confirmed.status,200,JSON.stringify(confirmed.data));assert.equal(confirmed.data.work.context.revision,2);assert.equal(confirmed.data.work.context.progress,"프로젝트 설명까지 했다");const replay=await call("/api/jarvis/voice/confirm",update.data.voice.confirmation);assert.equal(replay.status,200);assert.equal(replay.data.work.context.revision,2);
    const task=await call("/api/jarvis/voice/turns",{sessionId,providerItemId:"voice-task",requestId:randomUUID(),durationMs:800,messages:[{role:"user",content:'“성과 수치 정리” 할 일을 추가해.'}],contextId,expectedRevision:2});assert.equal(task.status,200,JSON.stringify(task.data));assert.equal(task.data.mode,"propose");const action=task.data.work.actions.find((value:{draft:{type:string}})=>value.draft.type==="CREATE_TASK");assert.ok(action);draftId=action.draft.id;const noTask=await admin.from("tasks").select("id",{count:"exact",head:true}).eq("title","성과 수치 정리");assert.equal(noTask.count,0);
    const approved=await call(`/api/jarvis/work-contexts/${contextId}/actions/${action.id}`,{decision:"approved"});assert.equal(approved.status,200,JSON.stringify(approved.data));approvalId=approved.data.work.actions.find((value:{id:string})=>value.id===action.id).approvalId;const again=await call(`/api/jarvis/work-contexts/${contextId}/actions/${action.id}`,{decision:"approved"});assert.equal(again.status,200);const tasks=await admin.from("tasks").select("id,title").eq("approval_request_id",approvalId);assert.ifError(tasks.error);assert.equal(tasks.data.length,1);assert.equal(tasks.data[0].title,"성과 수치 정리");const spoken=await call("/api/jarvis/voice/result-speech",{sessionId,turnId:task.data.voice.turnId,contextId,actionId:action.id});assert.equal(spoken.status,200);assert.match(spoken.data.speech.payload.text,/실행 결과가 확인됐습니다/);
  }finally{await browser.close();if(approvalId){await admin.from("tasks").delete().eq("approval_request_id",approvalId);await admin.from("action_audit_logs").delete().eq("approval_request_id",approvalId);}if(contextId){await admin.from("work_context_actions").delete().eq("context_id",contextId);await admin.from("work_context_requests").delete().eq("context_id",contextId);}if(draftId)await admin.from("dialogue_action_drafts").delete().eq("id",draftId);if(approvalId)await admin.from("approval_requests").delete().eq("id",approvalId);if(contextId)await admin.from("work_contexts").delete().eq("id",contextId);await admin.from("voice_sessions").delete().eq("id",sessionId);}
  const leaked=await admin.from("voice_turns").select("id",{count:"exact",head:true}).eq("owner_id",owner);assert.equal(leaked.count,0);
});
