import test from "node:test";
import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {config} from "dotenv";
import {createClient} from "@supabase/supabase-js";
import {chromium} from "playwright";
config({path:[".env.eval.local",".env.local"],quiet:true});
const url=process.env.NEXT_PUBLIC_SUPABASE_URL!,app="http://localhost:3055",admin=createClient(url,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false}});
test("G8 live OpenAI session contracts render both foreground modes without granting tools",{timeout:120000},async()=>{
  assert.equal(process.env.G8_ALLOW_LIVE_OPENAI,"1");assert.equal(url,"http://127.0.0.1:54721");await admin.from("voice_sessions" as never).delete().neq("id" as never,"00000000-0000-0000-0000-000000000000" as never);
  const link=await admin.auth.admin.generateLink({type:"magiclink",email:process.env.ALLOWED_EMAIL!});assert.ifError(link.error);const auth=createClient(url,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{auth:{persistSession:false}}),login=await auth.auth.verifyOtp({type:"email",email:process.env.ALLOWED_EMAIL!,token:link.data.properties.email_otp});assert.ifError(login.error);
  const browser=await chromium.launch({channel:"chrome",headless:true}),page=await browser.newPage({viewport:{width:390,height:844}});await page.context().addCookies([{name:"sb-127-auth-token",value:"base64-"+Buffer.from(JSON.stringify(login.data.session)).toString("base64url"),url:app}]);
  try{await page.goto(`${app}/jarvis`);await page.getByRole("heading",{name:"음성 JARVIS"}).waitFor();for(const mode of ["push_to_talk","automatic"]){const result=await page.evaluate(async mode=>{const r=await fetch("/api/jarvis/voice/sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode})});return{status:r.status,body:await r.json()};},mode);assert.equal(result.status,200,JSON.stringify(result.body));assert.equal(result.body.transcriptionModel,"gpt-live-transcribe");assert.ok(typeof result.body.clientSecret==="string"&&result.body.clientSecret.length>20);assert.equal("tools" in result.body,false);assert.equal(result.body.maxTurns,8);assert.equal(result.body.maxDurationSeconds,300);if(mode==="push_to_talk"){const turn=await page.evaluate(async input=>{const r=await fetch("/api/jarvis/voice/turns",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});return{status:r.status,body:await r.json()};},{sessionId:result.body.sessionId,providerItemId:"live-contract-item",requestId:randomUUID(),durationMs:500,messages:[{role:"user",content:"이어하자"}]});assert.equal(turn.status,200,JSON.stringify(turn.body));assert.ok(turn.body.voice.speech);const audio=await page.evaluate(async ticket=>{const r=await fetch("/api/jarvis/voice/speech",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(ticket)});return{status:r.status,type:r.headers.get("content-type"),bytes:(await r.arrayBuffer()).byteLength};},turn.body.voice.speech);assert.equal(audio.status,200);assert.equal(audio.type,"audio/pcm");assert.ok(audio.bytes>1000);}const ended=await page.evaluate(async id=>{const r=await fetch(`/api/jarvis/voice/sessions/${id}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:"live_contract_test"})});return r.status;},result.body.sessionId);assert.equal(ended,200);}}
  finally{await browser.close();await admin.from("voice_sessions" as never).delete().eq("owner_id" as never,login.data.user!.id as never);}
});
