import test from "node:test";
import assert from "node:assert/strict";
import { buildActionSpeech,buildReplySpeech,reduceVoiceState,signMutation,signSpeech,validateVoiceMode,verifyMutation,verifySpeech,voiceTranscriptionKeywords,voiceTurnDetection } from "../lib/jarvis/voice";
import type { WorkChatReply,WorkSnapshot } from "../lib/jarvis/work-types";

const old={secret:process.env.VOICE_SIGNING_SECRET,voice:process.env.JARVIS_VOICE_ENABLED,auto:process.env.JARVIS_VOICE_AUTO_TURN_ENABLED};
test.beforeEach(()=>{process.env.VOICE_SIGNING_SECRET="v".repeat(64);process.env.JARVIS_VOICE_ENABLED="true";process.env.JARVIS_VOICE_AUTO_TURN_ENABLED="true";});
test.after(()=>{for(const[key,value]of Object.entries(old)){const name=key==="secret"?"VOICE_SIGNING_SECRET":key==="voice"?"JARVIS_VOICE_ENABLED":"JARVIS_VOICE_AUTO_TURN_ENABLED";if(value===undefined)delete process.env[name];else process.env[name]=value;}});

test("voice state machine rejects impossible jumps and supports the foreground loop",()=>{let state=reduceVoiceState("idle",{type:"request_permission"});state=reduceVoiceState(state,{type:"permission_granted"});state=reduceVoiceState(state,{type:"connected"});state=reduceVoiceState(state,{type:"speech_stopped"});state=reduceVoiceState(state,{type:"transcript_final"});state=reduceVoiceState(state,{type:"speech_started_output"});state=reduceVoiceState(state,{type:"speech_finished"});assert.equal(state,"listening");assert.throws(()=>reduceVoiceState("idle",{type:"connected"}),/허용되지 않은/);});
test("PTT has no VAD while automatic mode uses bounded client-side silence detection",()=>{assert.equal(voiceTurnDetection(validateVoiceMode("push_to_talk")),null);assert.deepEqual(voiceTurnDetection(validateVoiceMode("automatic")),{type:"client_vad",rmsThreshold:.03,silenceDurationMs:700});process.env.JARVIS_VOICE_AUTO_TURN_ENABLED="false";assert.throws(()=>validateVoiceMode("automatic"),/활성화/);});
test("transcription keywords are bounded, deduplicated and use only current goal and next step",()=>{const values=voiceTranscriptionKeywords({goal:"Waseda 지원 / 성과 정리",nextStep:"GitHub 설명"});assert.ok(values.includes("Waseda"));assert.ok(values.includes("성과 정리"));assert.ok(values.includes("GitHub 설명"));assert.equal(new Set(values).size,values.length);assert.ok(values.length<=20);assert.ok(!voiceTranscriptionKeywords({goal:"<unsafe>",nextStep:"\ninvalid"}).includes("<unsafe>"));});
test("speech and mutation tickets reject tampering and expiry",()=>{const speech=signSpeech({sessionId:"s",turnId:"t",attempt:1,text:"확인된 결과",expiresAt:"2030-01-01T00:00:00Z"});assert.equal(verifySpeech(speech,new Date("2029-01-01")).text,"확인된 결과");assert.throws(()=>verifySpeech({...speech,payload:{...speech.payload,text:"임의 문장"}},new Date("2029-01-01")));assert.throws(()=>verifySpeech(speech,new Date("2031-01-01")));const mutation=signMutation({operation:"status",sessionId:"s",turnId:"t",contextId:"c",expectedRevision:2,requestId:"r",input:{status:"paused"},expiresAt:"2030-01-01T00:00:00Z"});assert.equal(verifyMutation(mutation,new Date("2029-01-01")).expectedRevision,2);assert.throws(()=>verifyMutation({...mutation,payload:{...mutation.payload,expectedRevision:3}},new Date("2029-01-01")));});
test("spoken output is bounded and derives proposals and verified action state",()=>{const reply:WorkChatReply={mode:"propose",message:"검토",work:null,preview:null,requestId:"r",proposals:[{id:"d",type:"CREATE_CALENDAR_EVENT",title:"면접 준비",explanation:"",payload:{summary:"면접 준비",startsAt:"2030-01-15T11:00:00Z",endsAt:"2030-01-15T11:30:00Z"},expiresAt:"2030-01-01T00:00:00Z",canRequestApproval:true}]};assert.match(buildReplySpeech(reply),/면접 준비/);assert.match(buildReplySpeech(reply),/승인 전/);const work={context:{id:"c"},actions:[{id:"a",status:"executed",draft:reply.proposals[0]}]} as unknown as WorkSnapshot;const spoken=buildActionSpeech(work,"a");assert.match(spoken,/실행 결과가 확인/);assert.match(spoken,/업무 전체 완료를 뜻하지 않습니다/);assert.ok(spoken.length<=350);});
