import type { CellDef, LabExerciseDef } from "../types";

function c(value: string | number | null): CellDef {
  return { value };
}

export const PHASE1: LabExerciseDef[] = [
  {
    id: "nav-cell-ref",
    moduleSlug: "nav",
    title: "셀 참조로 금액 구하기",
    instruction:
      "C2에 수량(A2)과 단가(B2)를 곱하는 수식을 입력하세요. 값을 직접 쓰지 말고 =A2*B2 형태를 씁니다.",
    columnCount: 3,
    rowCount: 2,
    initialGrid: [
      [c("수량"), c("단가"), c("금액")],
      [c(10), c(2500), c(null)],
    ],
    editableCells: [{ row: 1, col: 2 }],
    validations: [
      {
        cell: { row: 1, col: 2 },
        expectedValue: 25000,
        acceptFormula: /^=/,
        successMessage: "셀 참조 수식이 맞습니다.",
      },
    ],
    hints: ["수식은 =로 시작합니다", "C2에 =A2*B2를 입력하세요"],
    difficulty: 1,
  },
  {
    id: "basic-fn-sum",
    moduleSlug: "basic-fn",
    title: "SUM으로 합계 구하기",
    instruction:
      "B5, C5, D5에 각 분기 합계를 SUM으로 구하세요. 예: =SUM(B2:B4)",
    columnCount: 4,
    rowCount: 5,
    initialGrid: [
      [c("제품"), c("1분기"), c("2분기"), c("3분기")],
      [c("노트북"), c(1200), c(1500), c(1100)],
      [c("태블릿"), c(800), c(950), c(700)],
      [c("폰"), c(2300), c(2100), c(2500)],
      [c("합계"), c(null), c(null), c(null)],
    ],
    editableCells: [
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
    ],
    validations: [
      {
        cell: { row: 4, col: 1 },
        expectedValue: 4300,
        acceptFormula: /^=SUM\(/i,
        successMessage: "1분기 합계가 맞습니다.",
      },
      {
        cell: { row: 4, col: 2 },
        expectedValue: 4550,
        acceptFormula: /^=SUM\(/i,
        successMessage: "2분기 합계가 맞습니다.",
      },
      {
        cell: { row: 4, col: 3 },
        expectedValue: 4300,
        acceptFormula: /^=SUM\(/i,
        successMessage: "3분기 합계가 맞습니다.",
      },
    ],
    hints: ["SUM(시작:끝) 형태입니다", "=SUM(B2:B4)를 시도해 보세요"],
    difficulty: 1,
  },
  {
    id: "basic-fn-average",
    moduleSlug: "basic-fn",
    title: "AVERAGE로 평균 구하기",
    instruction: "B5:D5에 각 분기 평균을 AVERAGE로 구하세요.",
    columnCount: 4,
    rowCount: 5,
    initialGrid: [
      [c("제품"), c("1분기"), c("2분기"), c("3분기")],
      [c("노트북"), c(1200), c(1500), c(1100)],
      [c("태블릿"), c(800), c(950), c(700)],
      [c("폰"), c(2300), c(2100), c(2500)],
      [c("평균"), c(null), c(null), c(null)],
    ],
    editableCells: [
      { row: 4, col: 1 },
      { row: 4, col: 2 },
      { row: 4, col: 3 },
    ],
    validations: [
      {
        cell: { row: 4, col: 1 },
        expectedValue: 1433.33333333,
        acceptFormula: /^=AVERAGE\(/i,
        successMessage: "1분기 평균이 맞습니다.",
      },
      {
        cell: { row: 4, col: 2 },
        expectedValue: 1516.66666667,
        acceptFormula: /^=AVERAGE\(/i,
        successMessage: "2분기 평균이 맞습니다.",
      },
      {
        cell: { row: 4, col: 3 },
        expectedValue: 1433.33333333,
        acceptFormula: /^=AVERAGE\(/i,
        successMessage: "3분기 평균이 맞습니다.",
      },
    ],
    hints: ["AVERAGE(시작:끝)입니다", "=AVERAGE(B2:B4)를 입력하세요"],
    difficulty: 1,
  },
  {
    id: "basic-fn-count",
    moduleSlug: "basic-fn",
    title: "COUNT와 COUNTA",
    instruction:
      "B7에 COUNT(B2:B6), B8에 COUNTA(B2:B6)를 입력하세요. COUNT는 숫자만, COUNTA는 비어 있지 않은 셀 전부입니다.",
    columnCount: 2,
    rowCount: 8,
    initialGrid: [
      [c("항목"), c("값")],
      [c("노트북"), c(1200)],
      [c("태블릿"), c(800)],
      [c("빈칸"), c(null)],
      [c("폰"), c(2300)],
      [c("메모"), c("재고없음")],
      [c("COUNT"), c(null)],
      [c("COUNTA"), c(null)],
    ],
    editableCells: [
      { row: 6, col: 1 },
      { row: 7, col: 1 },
    ],
    validations: [
      {
        cell: { row: 6, col: 1 },
        expectedValue: 3,
        acceptFormula: /^=COUNT\(/i,
        successMessage: "숫자 셀 3개가 맞습니다.",
      },
      {
        cell: { row: 7, col: 1 },
        expectedValue: 4,
        acceptFormula: /^=COUNTA\(/i,
        successMessage: "비어 있지 않은 셀 4개가 맞습니다.",
      },
    ],
    hints: ["COUNT는 숫자만 셉니다", "B8에는 =COUNTA(B2:B6)"],
    difficulty: 1,
  },
  {
    id: "basic-fn-large",
    moduleSlug: "basic-fn",
    title: "LARGE로 상위 값 구하기",
    instruction: "B6에 1등 매출, B7에 2등 매출을 LARGE로 구하세요.",
    columnCount: 2,
    rowCount: 7,
    initialGrid: [
      [c("제품"), c("매출")],
      [c("A"), c(1200)],
      [c("B"), c(3500)],
      [c("C"), c(800)],
      [c("D"), c(2100)],
      [c("1위"), c(null)],
      [c("2위"), c(null)],
    ],
    editableCells: [
      { row: 5, col: 1 },
      { row: 6, col: 1 },
    ],
    validations: [
      {
        cell: { row: 5, col: 1 },
        expectedValue: 3500,
        acceptFormula: /^=LARGE\(/i,
        successMessage: "최댓값이 맞습니다.",
      },
      {
        cell: { row: 6, col: 1 },
        expectedValue: 2100,
        acceptFormula: /^=LARGE\(/i,
        successMessage: "두 번째로 큰 값이 맞습니다.",
      },
    ],
    hints: ["LARGE(범위, k)입니다", "=LARGE(B2:B5,2)가 2위입니다"],
    difficulty: 1,
  },
  {
    id: "basic-fn-mixed-ref",
    moduleSlug: "basic-fn",
    title: "혼합·절대참조로 세액 구하기",
    instruction:
      "C3과 C4에 매출×세율을 구하세요. 세율은 $C$1처럼 절대참조로 고정합니다.",
    columnCount: 3,
    rowCount: 4,
    initialGrid: [
      [c(""), c("세율"), c(0.1)],
      [c("제품"), c("매출"), c("세액")],
      [c("노트북"), c(1000), c(null)],
      [c("태블릿"), c(2000), c(null)],
    ],
    editableCells: [
      { row: 2, col: 2 },
      { row: 3, col: 2 },
    ],
    validations: [
      {
        cell: { row: 2, col: 2 },
        expectedValue: 100,
        acceptFormula: /\$C\$1/i,
        successMessage: "노트북 세액이 맞습니다.",
      },
      {
        cell: { row: 3, col: 2 },
        expectedValue: 200,
        acceptFormula: /\$C\$1/i,
        successMessage: "태블릿 세액이 맞습니다.",
      },
    ],
    hints: ["$는 행·열을 고정합니다", "C3에 =B3*$C$1 을 입력하세요"],
    difficulty: 2,
  },
  {
    id: "logic-if",
    moduleSlug: "logic",
    title: "IF로 합격 판정",
    instruction:
      "C2:C5에 점수가 70 이상이면 합격, 아니면 불합격인 IF를 입력하세요.",
    columnCount: 3,
    rowCount: 5,
    initialGrid: [
      [c("이름"), c("점수"), c("결과")],
      [c("김철수"), c(85), c(null)],
      [c("이영희"), c(62), c(null)],
      [c("박민수"), c(91), c(null)],
      [c("최지은"), c(45), c(null)],
    ],
    editableCells: [
      { row: 1, col: 2 },
      { row: 2, col: 2 },
      { row: 3, col: 2 },
      { row: 4, col: 2 },
    ],
    validations: [
      {
        cell: { row: 1, col: 2 },
        expectedValue: "합격",
        acceptFormula: /^=IF\(/i,
        successMessage: "김철수 합격이 맞습니다.",
      },
      {
        cell: { row: 2, col: 2 },
        expectedValue: "불합격",
        acceptFormula: /^=IF\(/i,
        successMessage: "이영희 불합격이 맞습니다.",
      },
      {
        cell: { row: 3, col: 2 },
        expectedValue: "합격",
        acceptFormula: /^=IF\(/i,
        successMessage: "박민수 합격이 맞습니다.",
      },
      {
        cell: { row: 4, col: 2 },
        expectedValue: "불합격",
        acceptFormula: /^=IF\(/i,
        successMessage: "최지은 불합격이 맞습니다.",
      },
    ],
    hints: ["IF(조건, 참값, 거짓값)", '=IF(B2>=70,"합격","불합격")'],
    difficulty: 1,
  },
  {
    id: "logic-nested-if",
    moduleSlug: "logic",
    title: "중첩 IF로 등급 매기기",
    instruction:
      "C2:C5에 90 이상 A, 70 이상 B, 50 이상 C, 그 외 F인 중첩 IF를 입력하세요.",
    columnCount: 3,
    rowCount: 5,
    initialGrid: [
      [c("이름"), c("점수"), c("등급")],
      [c("김철수"), c(92), c(null)],
      [c("이영희"), c(75), c(null)],
      [c("박민수"), c(55), c(null)],
      [c("최지은"), c(40), c(null)],
    ],
    editableCells: [
      { row: 1, col: 2 },
      { row: 2, col: 2 },
      { row: 3, col: 2 },
      { row: 4, col: 2 },
    ],
    validations: [
      {
        cell: { row: 1, col: 2 },
        expectedValue: "A",
        acceptFormula: /^=IF\(/i,
        successMessage: "92점은 A입니다.",
      },
      {
        cell: { row: 2, col: 2 },
        expectedValue: "B",
        acceptFormula: /^=IF\(/i,
        successMessage: "75점은 B입니다.",
      },
      {
        cell: { row: 3, col: 2 },
        expectedValue: "C",
        acceptFormula: /^=IF\(/i,
        successMessage: "55점은 C입니다.",
      },
      {
        cell: { row: 4, col: 2 },
        expectedValue: "F",
        acceptFormula: /^=IF\(/i,
        successMessage: "40점은 F입니다.",
      },
    ],
    hints: [
      "IF 안에 IF를 넣습니다",
      '=IF(B2>=90,"A",IF(B2>=70,"B",IF(B2>=50,"C","F")))',
    ],
    difficulty: 2,
  },
  {
    id: "logic-iferror",
    moduleSlug: "logic",
    title: "IFERROR로 #N/A 대체",
    instruction:
      "B5에 VLOOKUP이 실패하면 \"없음\"을 보이게 IFERROR를 쓰세요. 정확 일치 인수는 0입니다.",
    columnCount: 2,
    rowCount: 5,
    initialGrid: [
      [c("코드"), c("이름")],
      [c("A100"), c("노트북")],
      [c("A200"), c("태블릿")],
      [c("조회"), c("A999")],
      [c("안전조회"), c(null)],
    ],
    editableCells: [{ row: 4, col: 1 }],
    validations: [
      {
        cell: { row: 4, col: 1 },
        expectedValue: "없음",
        acceptFormula: /^=IFERROR\(/i,
        successMessage: "없는 코드를 안전하게 처리했습니다.",
      },
    ],
    hints: [
      "IFERROR(수식, 대체값)",
      '=IFERROR(VLOOKUP(B4,A2:B3,2,0),"없음")',
    ],
    difficulty: 2,
  },
  {
    id: "logic-sumif",
    moduleSlug: "logic",
    title: "SUMIF로 조건부 합계",
    instruction: "B6에 지역이 서울인 행의 매출 합계를 SUMIF로 구하세요.",
    columnCount: 3,
    rowCount: 6,
    initialGrid: [
      [c("지역"), c("매출"), c("구분")],
      [c("서울"), c(100), c("제품")],
      [c("부산"), c(80), c("제품")],
      [c("서울"), c(120), c("서비스")],
      [c("서울"), c(50), c("제품")],
      [c("서울합계"), c(null), c("")],
    ],
    editableCells: [{ row: 5, col: 1 }],
    validations: [
      {
        cell: { row: 5, col: 1 },
        expectedValue: 270,
        acceptFormula: /^=SUMIF\(/i,
        successMessage: "서울 매출 합계 270이 맞습니다.",
      },
    ],
    hints: ["SUMIF(조건범위, 조건, 합산범위)", '=SUMIF(A2:A5,"서울",B2:B5)'],
    difficulty: 2,
  },
  {
    id: "logic-countifs",
    moduleSlug: "logic",
    title: "COUNTIFS로 복수 조건 세기",
    instruction: "B6에 서울이면서 제품인 행 수를 COUNTIFS로 구하세요.",
    columnCount: 3,
    rowCount: 6,
    initialGrid: [
      [c("지역"), c("구분"), c("매출")],
      [c("서울"), c("제품"), c(100)],
      [c("부산"), c("제품"), c(80)],
      [c("서울"), c("서비스"), c(120)],
      [c("서울"), c("제품"), c(50)],
      [c("건수"), c(null), c("")],
    ],
    editableCells: [{ row: 5, col: 1 }],
    validations: [
      {
        cell: { row: 5, col: 1 },
        expectedValue: 2,
        acceptFormula: /^=COUNTIFS\(/i,
        successMessage: "서울·제품 2건이 맞습니다.",
      },
    ],
    hints: [
      "COUNTIFS(범위1, 조건1, 범위2, 조건2)",
      '=COUNTIFS(A2:A5,"서울",B2:B5,"제품")',
    ],
    difficulty: 2,
  },
  {
    id: "lookup-vlookup",
    moduleSlug: "lookup",
    title: "VLOOKUP으로 이름·단가 찾기",
    instruction:
      "B6에 이름, B7에 단가를 VLOOKUP으로 찾으세요. 4번째 인수는 정확 일치 0입니다 (FALSE 대신 0).",
    columnCount: 3,
    rowCount: 7,
    initialGrid: [
      [c("코드"), c("이름"), c("단가")],
      [c("A100"), c("노트북"), c(1200)],
      [c("A200"), c("태블릿"), c(800)],
      [c("A300"), c("폰"), c(2300)],
      [c("조회"), c("A200"), c("")],
      [c("이름"), c(null), c("")],
      [c("단가"), c(null), c("")],
    ],
    editableCells: [
      { row: 5, col: 1 },
      { row: 6, col: 1 },
    ],
    validations: [
      {
        cell: { row: 5, col: 1 },
        expectedValue: "태블릿",
        acceptFormula: /^=VLOOKUP\(/i,
        successMessage: "A200의 이름이 맞습니다.",
      },
      {
        cell: { row: 6, col: 1 },
        expectedValue: 800,
        acceptFormula: /^=VLOOKUP\(/i,
        successMessage: "A200의 단가가 맞습니다.",
      },
    ],
    hints: [
      "VLOOKUP(값, 범위, 열번호, 0)",
      "=VLOOKUP(B5,A2:C4,2,0) 그리고 열번호 3",
    ],
    difficulty: 2,
  },
  {
    id: "lookup-match",
    moduleSlug: "lookup",
    title: "MATCH로 위치 찾기",
    instruction: "B6에 A300이 A2:A4에서 몇 번째인지 MATCH로 구하세요. 유형은 0(정확 일치).",
    columnCount: 2,
    rowCount: 6,
    initialGrid: [
      [c("코드"), c("")],
      [c("A100"), c("")],
      [c("A200"), c("")],
      [c("A300"), c("")],
      [c("찾을값"), c("A300")],
      [c("위치"), c(null)],
    ],
    editableCells: [{ row: 5, col: 1 }],
    validations: [
      {
        cell: { row: 5, col: 1 },
        expectedValue: 3,
        acceptFormula: /^=MATCH\(/i,
        successMessage: "세 번째 행이 맞습니다.",
      },
    ],
    hints: ["MATCH(값, 범위, 0)", "=MATCH(B5,A2:A4,0)"],
    difficulty: 1,
  },
  {
    id: "lookup-index-match",
    moduleSlug: "lookup",
    title: "INDEX-MATCH로 단가 찾기",
    instruction: "B6에 A300의 단가를 INDEX+MATCH로 구하세요. VLOOKUP은 쓰지 않습니다.",
    columnCount: 3,
    rowCount: 6,
    initialGrid: [
      [c("코드"), c("이름"), c("단가")],
      [c("A100"), c("노트북"), c(1200)],
      [c("A200"), c("태블릿"), c(800)],
      [c("A300"), c("폰"), c(2300)],
      [c("조회"), c("A300"), c("")],
      [c("단가"), c(null), c("")],
    ],
    editableCells: [{ row: 5, col: 1 }],
    validations: [
      {
        cell: { row: 5, col: 1 },
        expectedValue: 2300,
        acceptFormula: /^=INDEX\(/i,
        successMessage: "INDEX-MATCH 단가가 맞습니다.",
      },
    ],
    hints: [
      "INDEX(반환범위, MATCH(값, 조회범위, 0))",
      "=INDEX(C2:C4,MATCH(B5,A2:A4,0))",
    ],
    difficulty: 2,
  },
  {
    id: "lookup-2d",
    moduleSlug: "lookup",
    title: "INDEX-MATCH-MATCH 2차원 조회",
    instruction: "B7에 Beta의 2023 매출을 INDEX-MATCH-MATCH로 구하세요.",
    columnCount: 4,
    rowCount: 7,
    initialGrid: [
      [c("회사"), c(2022), c(2023), c(2024)],
      [c("Alpha"), c(100), c(120), c(140)],
      [c("Beta"), c(80), c(90), c(110)],
      [c("Gamma"), c(200), c(180), c(210)],
      [c("회사"), c("Beta"), c(""), c("")],
      [c("연도"), c(2023), c(""), c("")],
      [c("매출"), c(null), c(""), c("")],
    ],
    editableCells: [{ row: 6, col: 1 }],
    validations: [
      {
        cell: { row: 6, col: 1 },
        expectedValue: 90,
        acceptFormula: /^=INDEX\(/i,
        successMessage: "Beta 2023 매출 90이 맞습니다.",
      },
    ],
    hints: [
      "INDEX(데이터, 행MATCH, 열MATCH)",
      "=INDEX(B2:D4,MATCH(B5,A2:A4,0),MATCH(B6,B1:D1,0))",
    ],
    difficulty: 3,
  },
];
