import type { LabExerciseDef } from "../types";
import { gridLab } from "./lab";

const XNPV = /^=XNPV\(/i;
const XIRR = /^=XIRR\(/i;
const IPMT = /^=IPMT\(/i;
const PPMT = /^=PPMT\(/i;
const NPER = /^=NPER\(/i;

export const VOLUME2: LabExerciseDef[] = [
  gridLab({
    id: "fin-xnpv",
    moduleSlug: "fin-fn",
    title: "XNPV 날짜 할인",
    instruction:
      "B7에 할인율 B1과 CF A3:A6, 날짜 B3:B6으로 XNPV를 구하세요. 날짜는 엑셀 일련번호입니다. DATE() 셀을 넣으면 이 엔진의 XNPV가 #VALUE!입니다.",
    difficulty: 3,
    grid: [
      ["할인율", 0.1],
      ["CF", "날짜"],
      [-1000, 45292],
      [400, 45383],
      [400, 45505],
      [400, 45658],
      ["XNPV", null],
    ],
    editable: [[6, 1]],
    validations: [
      {
        row: 6,
        col: 1,
        expected: 132.50819997,
        re: XNPV,
        msg: "XNPV가 맞습니다.",
        tolerance: 0.01,
      },
    ],
    hints: [
      "XNPV(할인율, 현금흐름, 날짜)",
      "=XNPV(B1,A3:A6,B3:B6) · 2024-01-01 일련번호는 45292",
    ],
  }),
  gridLab({
    id: "fin-xnpv-uneven",
    moduleSlug: "fin-fn",
    title: "XNPV 불규칙 CF",
    instruction: "B7에 금액이 다른 CF의 XNPV를 구하세요.",
    difficulty: 3,
    grid: [
      ["할인율", 0.1],
      ["CF", "날짜"],
      [-1000, 45292],
      [300, 45383],
      [500, 45505],
      [400, 45658],
      ["XNPV", null],
    ],
    editable: [[6, 1]],
    validations: [
      {
        row: 6,
        col: 1,
        expected: 129.44632736,
        re: XNPV,
        msg: "불규칙 CF XNPV가 맞습니다.",
        tolerance: 0.01,
      },
    ],
    hints: ["=XNPV(B1,A3:A6,B3:B6)"],
  }),
  gridLab({
    id: "fin-xnpv-12",
    moduleSlug: "fin-fn",
    title: "XNPV 12% 할인",
    instruction: "B7에 할인율 12%로 XNPV를 구하세요. 할인율은 B1을 참조하세요.",
    difficulty: 3,
    grid: [
      ["할인율", 0.12],
      ["CF", "날짜"],
      [-1000, 45292],
      [400, 45383],
      [400, 45505],
      [400, 45658],
      ["XNPV", null],
    ],
    editable: [[6, 1]],
    validations: [
      {
        row: 6,
        col: 1,
        expected: 120.2904063,
        re: XNPV,
        msg: "12% XNPV가 맞습니다.",
        tolerance: 0.01,
      },
    ],
    hints: ["=XNPV(B1,A3:A6,B3:B6)"],
  }),
  gridLab({
    id: "fin-xirr",
    moduleSlug: "fin-fn",
    title: "XIRR 날짜 수익률",
    instruction: "B7에 A3:A6과 날짜 B3:B6의 XIRR을 구하세요. 날짜는 DATE 수식이어도 됩니다.",
    difficulty: 3,
    grid: [
      ["항목", "값"],
      ["CF", "날짜"],
      [-1000, "=DATE(2024,1,1)"],
      [400, "=DATE(2024,4,1)"],
      [400, "=DATE(2024,8,1)"],
      [400, "=DATE(2025,1,1)"],
      ["XIRR", null],
    ],
    editable: [[6, 1]],
    validations: [
      {
        row: 6,
        col: 1,
        expected: 0.35684805638,
        re: XIRR,
        msg: "XIRR이 맞습니다.",
        tolerance: 0.001,
      },
    ],
    hints: ["XIRR(현금흐름, 날짜)", "=XIRR(A3:A6,B3:B6)"],
  }),
  gridLab({
    id: "fin-xirr-uneven",
    moduleSlug: "fin-fn",
    title: "XIRR 불규칙 CF",
    instruction: "B6에 일련번호 날짜와 불규칙 CF의 XIRR을 구하세요.",
    difficulty: 3,
    grid: [
      ["CF", "날짜"],
      [-1000, 45292],
      [300, 45383],
      [500, 45505],
      [400, 45658],
      ["XIRR", null],
    ],
    editable: [[5, 1]],
    validations: [
      {
        row: 5,
        col: 1,
        expected: 0.33707663896,
        re: XIRR,
        msg: "불규칙 CF XIRR이 맞습니다.",
        tolerance: 0.001,
      },
    ],
    hints: ["=XIRR(A2:A5,B2:B5)"],
  }),
  gridLab({
    id: "fin-ipmt",
    moduleSlug: "fin-fn",
    title: "IPMT 첫 달 이자",
    instruction:
      "B5에 1회차 이자(IPMT)를 구하세요. 월이율=연이율/12, 기간=년*12, 원금은 음수입니다.",
    difficulty: 2,
    grid: [
      ["항목", "값"],
      ["대출 원금", 500000000],
      ["연 이자율", 0.05],
      ["기간(년)", 30],
      ["1회 이자", null],
    ],
    editable: [[4, 1]],
    validations: [
      {
        row: 4,
        col: 1,
        expected: 2083333.3333,
        re: IPMT,
        msg: "첫 달 이자가 맞습니다.",
        tolerance: 1.0,
      },
    ],
    hints: ["IPMT(이율, 회차, 기간수, 현재가치)", "=IPMT(B3/12,1,B4*12,-B2)"],
  }),
  gridLab({
    id: "fin-ipmt-12",
    moduleSlug: "fin-fn",
    title: "IPMT 12회차 이자",
    instruction: "B5에 12회차 이자를 IPMT로 구하세요.",
    difficulty: 2,
    grid: [
      ["항목", "값"],
      ["대출 원금", 500000000],
      ["연 이자율", 0.05],
      ["기간(년)", 30],
      ["12회 이자", null],
    ],
    editable: [[4, 1]],
    validations: [
      {
        row: 4,
        col: 1,
        expected: 2055216.9352,
        re: IPMT,
        msg: "12회차 이자가 맞습니다.",
        tolerance: 1.0,
      },
    ],
    hints: ["=IPMT(B3/12,12,B4*12,-B2)"],
  }),
  gridLab({
    id: "fin-ipmt-last",
    moduleSlug: "fin-fn",
    title: "IPMT 마지막 회차",
    instruction: "B5에 360회차(마지막) 이자를 IPMT로 구하세요.",
    difficulty: 2,
    grid: [
      ["항목", "값"],
      ["대출 원금", 500000000],
      ["연 이자율", 0.05],
      ["기간(년)", 30],
      ["마지막 이자", null],
    ],
    editable: [[4, 1]],
    validations: [
      {
        row: 4,
        col: 1,
        expected: 11137.378071,
        re: IPMT,
        msg: "마지막 회차 이자가 맞습니다.",
        tolerance: 1.0,
      },
    ],
    hints: ["=IPMT(B3/12,360,B4*12,-B2)"],
  }),
  gridLab({
    id: "fin-ppmt",
    moduleSlug: "fin-fn",
    title: "PPMT 첫 달 원금",
    instruction: "B5에 1회차 원금 상환(PPMT)을 구하세요. 원금은 음수로 넣습니다.",
    difficulty: 2,
    grid: [
      ["항목", "값"],
      ["대출 원금", 500000000],
      ["연 이자율", 0.05],
      ["기간(년)", 30],
      ["1회 원금", null],
    ],
    editable: [[4, 1]],
    validations: [
      {
        row: 4,
        col: 1,
        expected: 600774.78173,
        re: PPMT,
        msg: "첫 달 원금이 맞습니다.",
        tolerance: 1.0,
      },
    ],
    hints: ["PPMT(이율, 회차, 기간수, 현재가치)", "=PPMT(B3/12,1,B4*12,-B2)"],
  }),
  gridLab({
    id: "fin-ppmt-12",
    moduleSlug: "fin-fn",
    title: "PPMT 12회차 원금",
    instruction: "B5에 12회차 원금 상환을 PPMT로 구하세요.",
    difficulty: 2,
    grid: [
      ["항목", "값"],
      ["대출 원금", 500000000],
      ["연 이자율", 0.05],
      ["기간(년)", 30],
      ["12회 원금", null],
    ],
    editable: [[4, 1]],
    validations: [
      {
        row: 4,
        col: 1,
        expected: 628891.17984,
        re: PPMT,
        msg: "12회차 원금이 맞습니다.",
        tolerance: 1.0,
      },
    ],
    hints: ["=PPMT(B3/12,12,B4*12,-B2)"],
  }),
  gridLab({
    id: "fin-nper",
    moduleSlug: "fin-fn",
    title: "NPER로 기간",
    instruction: "B5에 1천만 원이 12,762,816원이 되는 연 수를 NPER로 구하세요. 중간 납입은 0입니다.",
    difficulty: 2,
    grid: [
      ["항목", "값"],
      ["현재가치", 10000000],
      ["연 이자율", 0.05],
      ["미래가치", 12762816],
      ["기간(년)", null],
    ],
    editable: [[4, 1]],
    validations: [
      {
        row: 4,
        col: 1,
        expected: 5,
        re: NPER,
        msg: "약 5년이 맞습니다.",
        tolerance: 0.001,
      },
    ],
    hints: ["NPER(이율, 납입, -현재가치, 미래가치)", "=NPER(B3,0,-B2,B4)"],
  }),
  gridLab({
    id: "fin-nper-pmt",
    moduleSlug: "fin-fn",
    title: "NPER 월 적립",
    instruction: "B5에 월 10만 원으로 15,528,228원을 모으는 개월 수를 NPER로 구하세요. 월이율=5%/12.",
    difficulty: 2,
    grid: [
      ["항목", "값"],
      ["월 적립", 100000],
      ["연 이자율", 0.05],
      ["목표", 15528228],
      ["개월", null],
    ],
    editable: [[4, 1]],
    validations: [
      {
        row: 4,
        col: 1,
        expected: 120,
        re: NPER,
        msg: "120개월이 맞습니다.",
        tolerance: 0.01,
      },
    ],
    hints: ["=NPER(B3/12,-B2,0,B4)"],
  }),
];
