import type { LabExerciseDef } from "../types";
import { gridLab } from "./lab";

const AND = /^=IF\(AND\(/i;
const OR = /^=IF\(OR\(/i;
const IFS = /^=IFS\(/i;
const IFNA = /^=IFNA\(/i;
const SUMIFS = /^=SUMIFS\(/i;
const AVERAGEIF = /^=AVERAGEIF\(/i;
const SUMPRODUCT = /^=SUMPRODUCT\(/i;
const COUNTIF = /^=COUNTIF\(/i;
const XLOOKUP = /^=XLOOKUP\(/i;

export const VOLUME1: LabExerciseDef[] = [
  gridLab({
    id: "basic-fn-min",
    moduleSlug: "basic-fn",
    title: "MIN으로 최솟값",
    instruction: "B6에 B2:B5 매출의 최솟값을 MIN으로 구하세요.",
    difficulty: 1,
    grid: [
      ["제품", "매출"],
      ["A", 1200],
      ["B", 3500],
      ["C", 800],
      ["D", 2100],
      ["최소", null],
    ],
    editable: [[5, 1]],
    validations: [{ row: 5, col: 1, expected: 800, re: /^=MIN\(/i, msg: "최솟값 800이 맞습니다." }],
    hints: ["MIN(범위)", "=MIN(B2:B5)"],
  }),
  gridLab({
    id: "basic-fn-max",
    moduleSlug: "basic-fn",
    title: "MAX로 최댓값",
    instruction: "B6에 B2:B5 매출의 최댓값을 MAX로 구하세요.",
    difficulty: 1,
    grid: [
      ["제품", "매출"],
      ["A", 1200],
      ["B", 3500],
      ["C", 800],
      ["D", 2100],
      ["최대", null],
    ],
    editable: [[5, 1]],
    validations: [{ row: 5, col: 1, expected: 3500, re: /^=MAX\(/i, msg: "최댓값 3500이 맞습니다." }],
    hints: ["MAX(범위)", "=MAX(B2:B5)"],
  }),
  gridLab({
    id: "basic-fn-small",
    moduleSlug: "basic-fn",
    title: "SMALL로 하위 값",
    instruction: "B6에 가장 작은 값, B7에 두 번째로 작은 값을 SMALL로 구하세요.",
    difficulty: 1,
    grid: [
      ["제품", "매출"],
      ["A", 1200],
      ["B", 3500],
      ["C", 800],
      ["D", 2100],
      ["1위(작음)", null],
      ["2위(작음)", null],
    ],
    editable: [[5, 1], [6, 1]],
    validations: [
      { row: 5, col: 1, expected: 800, re: /^=SMALL\(/i, msg: "가장 작은 값이 맞습니다." },
      { row: 6, col: 1, expected: 1200, re: /^=SMALL\(/i, msg: "두 번째로 작은 값이 맞습니다." },
    ],
    hints: ["SMALL(범위, k)", "=SMALL(B2:B5,1) 그리고 =SMALL(B2:B5,2)"],
  }),
  gridLab({
    id: "basic-fn-small-k3",
    moduleSlug: "basic-fn",
    title: "SMALL k=3",
    instruction: "B6에 세 번째로 작은 매출을 SMALL로 구하세요.",
    difficulty: 1,
    grid: [
      ["제품", "매출"],
      ["A", 1200],
      ["B", 3500],
      ["C", 800],
      ["D", 2100],
      ["3위(작음)", null],
    ],
    editable: [[5, 1]],
    validations: [{ row: 5, col: 1, expected: 2100, re: /^=SMALL\(/i, msg: "세 번째로 작은 값 2100이 맞습니다." }],
    hints: ["k=3", "=SMALL(B2:B5,3)"],
  }),
  gridLab({
    id: "basic-fn-countblank",
    moduleSlug: "basic-fn",
    title: "COUNTBLANK로 빈 셀",
    instruction: "B7에 B2:B6의 빈 셀 수를 COUNTBLANK로 구하세요.",
    difficulty: 1,
    grid: [
      ["항목", "값"],
      ["노트북", 1200],
      ["태블릿", 800],
      ["빈칸", null],
      ["폰", 2300],
      ["메모", "재고없음"],
      ["빈 셀", null],
    ],
    editable: [[6, 1]],
    validations: [{ row: 6, col: 1, expected: 1, re: /^=COUNTBLANK\(/i, msg: "빈 셀 1개가 맞습니다." }],
    hints: ["COUNTBLANK(범위)", "=COUNTBLANK(B2:B6)"],
  }),
  gridLab({
    id: "basic-fn-countblank-mixed",
    moduleSlug: "basic-fn",
    title: "COUNTBLANK와 숫자 열",
    instruction: "B6에 A1:A5의 빈 칸 수를 COUNTBLANK로 구하세요.",
    difficulty: 1,
    grid: [
      [100, "빈 칸 수"],
      [120, null],
      [null, null],
      [90, null],
      [110, null],
      [null, null],
    ],
    editable: [[5, 1]],
    validations: [{ row: 5, col: 1, expected: 1, re: /^=COUNTBLANK\(/i, msg: "A1:A5 빈 칸 1개가 맞습니다." }],
    hints: ["범위는 A1:A5", "=COUNTBLANK(A1:A5)"],
  }),

  gridLab({
    id: "logic-and",
    moduleSlug: "logic",
    title: "AND로 승인 게이트",
    instruction: 'C2:C4에 서울이면서 매출 100 이상이면 "승인", 아니면 "보류"인 IF+AND를 입력하세요.',
    difficulty: 2,
    grid: [
      ["지역", "매출", "결과"],
      ["서울", 150, null],
      ["부산", 180, null],
      ["서울", 60, null],
    ],
    editable: [[1, 2], [2, 2], [3, 2]],
    validations: [
      { row: 1, col: 2, expected: "승인", re: AND, msg: "서울 150은 승인입니다." },
      { row: 2, col: 2, expected: "보류", re: AND, msg: "부산은 보류입니다." },
      { row: 3, col: 2, expected: "보류", re: AND, msg: "서울 60은 보류입니다." },
    ],
    hints: ["IF(AND(조건1, 조건2), 참, 거짓)", '=IF(AND(A2="서울",B2>=100),"승인","보류")'],
  }),
  gridLab({
    id: "logic-or",
    moduleSlug: "logic",
    title: "OR로 검토 대상",
    instruction: 'C2:C4에 서울이거나 매출 100 이상이면 "검토", 아니면 "대기"인 IF+OR를 입력하세요.',
    difficulty: 2,
    grid: [
      ["지역", "매출", "결과"],
      ["서울", 60, null],
      ["부산", 180, null],
      ["대구", 40, null],
    ],
    editable: [[1, 2], [2, 2], [3, 2]],
    validations: [
      { row: 1, col: 2, expected: "검토", re: OR, msg: "서울은 검토입니다." },
      { row: 2, col: 2, expected: "검토", re: OR, msg: "매출 180은 검토입니다." },
      { row: 3, col: 2, expected: "대기", re: OR, msg: "대구 40은 대기입니다." },
    ],
    hints: ["IF(OR(조건1, 조건2), 참, 거짓)", '=IF(OR(A2="서울",B2>=100),"검토","대기")'],
  }),
  gridLab({
    id: "logic-and-or",
    moduleSlug: "logic",
    title: "AND+OR 조합",
    instruction:
      'C2:C4에 (서울 또는 부산)이면서 매출 100 이상이면 "승인", 아니면 "보류"를 넣으세요.',
    difficulty: 2,
    grid: [
      ["지역", "매출", "결과"],
      ["서울", 150, null],
      ["부산", 80, null],
      ["대구", 200, null],
    ],
    editable: [[1, 2], [2, 2], [3, 2]],
    validations: [
      { row: 1, col: 2, expected: "승인", re: AND, msg: "서울 150은 승인입니다." },
      { row: 2, col: 2, expected: "보류", re: AND, msg: "부산 80은 보류입니다." },
      { row: 3, col: 2, expected: "보류", re: AND, msg: "대구는 지역 조건 밖입니다." },
    ],
    hints: [
      "AND 안에 OR를 넣습니다",
      '=IF(AND(OR(A2="서울",A2="부산"),B2>=100),"승인","보류")',
    ],
  }),
  gridLab({
    id: "logic-not",
    moduleSlug: "logic",
    title: "NOT으로 제외 플래그",
    instruction: 'C2:C4에 상태가 N이 아니면 "진행", N이면 "중단"인 IF+NOT을 입력하세요.',
    difficulty: 1,
    grid: [
      ["건", "상태", "결과"],
      ["1", "Y", null],
      ["2", "N", null],
      ["3", "Y", null],
    ],
    editable: [[1, 2], [2, 2], [3, 2]],
    validations: [
      { row: 1, col: 2, expected: "진행", re: /^=IF\(NOT\(/i, msg: "Y는 진행입니다." },
      { row: 2, col: 2, expected: "중단", re: /^=IF\(NOT\(/i, msg: "N은 중단입니다." },
      { row: 3, col: 2, expected: "진행", re: /^=IF\(NOT\(/i, msg: "Y는 진행입니다." },
    ],
    hints: ["NOT은 논리를 뒤집습니다", '=IF(NOT(B2="N"),"진행","중단")'],
  }),
  gridLab({
    id: "logic-and-3",
    moduleSlug: "logic",
    title: "AND 세 조건",
    instruction: 'D2:D3에 서울·제품·매출 100 이상이면 "통과"인 IF+AND를 입력하세요.',
    difficulty: 2,
    grid: [
      ["지역", "구분", "매출", "결과"],
      ["서울", "제품", 150, null],
      ["서울", "서비스", 200, null],
    ],
    editable: [[1, 3], [2, 3]],
    validations: [
      { row: 1, col: 3, expected: "통과", re: AND, msg: "세 조건이 맞습니다." },
      { row: 2, col: 3, expected: "보류", re: AND, msg: "서비스는 보류입니다." },
    ],
    hints: [
      "AND는 인수를 더 받을 수 있습니다",
      '=IF(AND(A2="서울",B2="제품",C2>=100),"통과","보류")',
    ],
  }),
  gridLab({
    id: "logic-or-3",
    moduleSlug: "logic",
    title: "OR 세 지역",
    instruction: 'C2:C4에 서울·부산·인천 중 하나면 "권역", 아니면 "기타"인 IF+OR를 입력하세요.',
    difficulty: 2,
    grid: [
      ["지역", "매출", "결과"],
      ["서울", 10, null],
      ["인천", 10, null],
      ["대전", 10, null],
    ],
    editable: [[1, 2], [2, 2], [3, 2]],
    validations: [
      { row: 1, col: 2, expected: "권역", re: OR, msg: "서울은 권역입니다." },
      { row: 2, col: 2, expected: "권역", re: OR, msg: "인천은 권역입니다." },
      { row: 3, col: 2, expected: "기타", re: OR, msg: "대전은 기타입니다." },
    ],
    hints: ['=IF(OR(A2="서울",A2="부산",A2="인천"),"권역","기타")'],
  }),
  gridLab({
    id: "logic-ifs",
    moduleSlug: "logic",
    title: "IFS로 등급",
    instruction:
      "C2:C5에 90 이상 A, 70 이상 B, 50 이상 C, 그 외 F인 IFS를 입력하세요. TRUE는 쓰지 마세요.",
    difficulty: 2,
    grid: [
      ["이름", "점수", "등급"],
      ["김철수", 92, null],
      ["이영희", 75, null],
      ["박민수", 55, null],
      ["최지은", 40, null],
    ],
    editable: [[1, 2], [2, 2], [3, 2], [4, 2]],
    validations: [
      { row: 1, col: 2, expected: "A", re: IFS, msg: "92점은 A입니다." },
      { row: 2, col: 2, expected: "B", re: IFS, msg: "75점은 B입니다." },
      { row: 3, col: 2, expected: "C", re: IFS, msg: "55점은 C입니다." },
      { row: 4, col: 2, expected: "F", re: IFS, msg: "40점은 F입니다." },
    ],
    hints: [
      "마지막 조건은 B2>=0처럼 항상 참인 비교를 씁니다. TRUE는 #NAME?입니다.",
      '=IFS(B2>=90,"A",B2>=70,"B",B2>=50,"C",B2>=0,"F")',
    ],
  }),
  gridLab({
    id: "logic-ifs-flag",
    moduleSlug: "logic",
    title: "IFS로 시나리오 라벨",
    instruction: 'C2:C4에 성장률 0.2 이상 Upside, 0 이상 Base, 그 외 Down인 IFS를 입력하세요.',
    difficulty: 2,
    grid: [
      ["케이스", "성장률", "라벨"],
      ["A", 0.25, null],
      ["B", 0.08, null],
      ["C", -0.05, null],
    ],
    editable: [[1, 2], [2, 2], [3, 2]],
    validations: [
      { row: 1, col: 2, expected: "Upside", re: IFS, msg: "0.25는 Upside입니다." },
      { row: 2, col: 2, expected: "Base", re: IFS, msg: "0.08은 Base입니다." },
      { row: 3, col: 2, expected: "Down", re: IFS, msg: "음수는 Down입니다." },
    ],
    hints: ['=IFS(B2>=0.2,"Upside",B2>=0,"Base",B2<0,"Down")'],
  }),
  gridLab({
    id: "logic-ifs-pass",
    moduleSlug: "logic",
    title: "IFS로 합격선",
    instruction: 'B5에 점수가 70 이상이면 "합격", 아니면 "불합격"인 IFS를 입력하세요.',
    difficulty: 1,
    grid: [
      ["이름", "점수"],
      ["김", 85],
      ["이", 62],
      ["조회", 85],
      ["결과", null],
    ],
    editable: [[4, 1]],
    validations: [
      { row: 4, col: 1, expected: "합격", re: IFS, msg: "85점은 합격입니다." },
    ],
    hints: ['=IFS(B4>=70,"합격",B4>=0,"불합격")'],
  }),
  gridLab({
    id: "logic-ifna",
    moduleSlug: "logic",
    title: "IFNA로 #N/A만 대체",
    instruction:
      'B5에 VLOOKUP이 #N/A면 "없음"을 보이게 IFNA를 쓰세요. 정확 일치는 0입니다.',
    difficulty: 2,
    grid: [
      ["코드", "이름"],
      ["A100", "노트북"],
      ["A200", "태블릿"],
      ["조회", "A999"],
      ["안전조회", null],
    ],
    editable: [[4, 1]],
    validations: [
      { row: 4, col: 1, expected: "없음", re: IFNA, msg: "없는 코드를 IFNA로 처리했습니다." },
    ],
    hints: ['IFNA(수식, 대체값)', '=IFNA(VLOOKUP(B4,A2:B3,2,0),"없음")'],
  }),
  gridLab({
    id: "logic-ifna-hit",
    moduleSlug: "logic",
    title: "IFNA 히트",
    instruction: "B5에 있는 코드 A100을 IFNA+VLOOKUP으로 찾으세요. 대체값은 쓰이지만 호출되지 않아야 합니다.",
    difficulty: 2,
    grid: [
      ["코드", "이름"],
      ["A100", "노트북"],
      ["A200", "태블릿"],
      ["조회", "A100"],
      ["안전조회", null],
    ],
    editable: [[4, 1]],
    validations: [
      { row: 4, col: 1, expected: "노트북", re: IFNA, msg: "있는 코드는 그대로 나옵니다." },
    ],
    hints: ['=IFNA(VLOOKUP(B4,A2:B3,2,0),"없음")'],
  }),
  gridLab({
    id: "logic-sumifs",
    moduleSlug: "logic",
    title: "SUMIFS 두 조건",
    instruction: "C6에 서울이면서 제품인 매출 합계를 SUMIFS로 구하세요. 합산 범위가 첫 인수입니다.",
    difficulty: 2,
    grid: [
      ["지역", "구분", "매출"],
      ["서울", "제품", 100],
      ["부산", "제품", 80],
      ["서울", "서비스", 120],
      ["서울", "제품", 50],
      ["합계", "", null],
    ],
    editable: [[5, 2]],
    validations: [
      { row: 5, col: 2, expected: 150, re: SUMIFS, msg: "서울·제품 150이 맞습니다." },
    ],
    hints: ['SUMIFS(합산, 범위1, 조건1, …)', '=SUMIFS(C2:C5,A2:A5,"서울",B2:B5,"제품")'],
  }),
  gridLab({
    id: "logic-sumifs-3",
    moduleSlug: "logic",
    title: "SUMIFS 세 조건",
    instruction: 'D6에 서울·노트북·2024 매출 합계를 SUMIFS로 구하세요.',
    difficulty: 2,
    grid: [
      ["지역", "제품", "연도", "매출"],
      ["서울", "노트북", 2024, 100],
      ["서울", "노트북", 2023, 80],
      ["부산", "노트북", 2024, 90],
      ["서울", "폰", 2024, 70],
      ["합계", "", "", null],
    ],
    editable: [[5, 3]],
    validations: [
      { row: 5, col: 3, expected: 100, re: SUMIFS, msg: "세 조건 합계 100이 맞습니다." },
    ],
    hints: ['=SUMIFS(D2:D5,A2:A5,"서울",B2:B5,"노트북",C2:C5,2024)'],
  }),
  gridLab({
    id: "logic-sumifs-gte",
    moduleSlug: "logic",
    title: "SUMIFS 이상 조건",
    instruction: 'C6에 서울이면서 매출 100 이상인 행의 합계를 SUMIFS로 구하세요.',
    difficulty: 2,
    grid: [
      ["지역", "구분", "매출"],
      ["서울", "제품", 100],
      ["부산", "제품", 180],
      ["서울", "서비스", 120],
      ["서울", "제품", 50],
      ["합계", "", null],
    ],
    editable: [[5, 2]],
    validations: [
      { row: 5, col: 2, expected: 220, re: SUMIFS, msg: "서울·100이상 220이 맞습니다." },
    ],
    hints: ['숫자 조건은 ">="&100', '=SUMIFS(C2:C5,A2:A5,"서울",C2:C5,">="&100)'],
  }),
  gridLab({
    id: "logic-averageif",
    moduleSlug: "logic",
    title: "AVERAGEIF 지역 평균",
    instruction: "B6에 서울 매출 평균을 AVERAGEIF로 구하세요. AVERAGEIFS는 이 엔진에 없습니다.",
    difficulty: 2,
    grid: [
      ["지역", "매출"],
      ["서울", 100],
      ["부산", 80],
      ["서울", 120],
      ["서울", 50],
      ["서울평균", null],
    ],
    editable: [[5, 1]],
    validations: [
      { row: 5, col: 1, expected: 90, re: AVERAGEIF, msg: "서울 평균 90이 맞습니다." },
    ],
    hints: ['AVERAGEIF(조건범위, 조건, 평균범위)', '=AVERAGEIF(A2:A5,"서울",B2:B5)'],
  }),
  gridLab({
    id: "logic-averageif-gte",
    moduleSlug: "logic",
    title: "AVERAGEIF 임계값",
    instruction: 'B6에 100 이상인 값의 평균을 AVERAGEIF로 구하세요.',
    difficulty: 2,
    grid: [
      ["값", ""],
      [80, ""],
      [120, ""],
      [150, ""],
      [90, ""],
      ["평균", null],
    ],
    editable: [[5, 1]],
    validations: [
      { row: 5, col: 1, expected: 135, re: AVERAGEIF, msg: "100 이상 평균 135가 맞습니다." },
    ],
    hints: ['=AVERAGEIF(A2:A5,">=100")'],
  }),
  gridLab({
    id: "logic-sumproduct",
    moduleSlug: "logic",
    title: "SUMPRODUCT 수량×단가",
    instruction: "B5에 수량×단가의 합을 SUMPRODUCT로 구하세요. 배열 조건식은 이 엔진에서 #VALUE!입니다.",
    difficulty: 2,
    grid: [
      ["수량", "단가"],
      [10, 2500],
      [4, 800],
      [6, 1200],
      ["합계", null],
    ],
    editable: [[4, 1]],
    validations: [
      { row: 4, col: 1, expected: 35400, re: SUMPRODUCT, msg: "수량×단가 합 35400이 맞습니다." },
    ],
    hints: ["SUMPRODUCT(배열1, 배열2)", "=SUMPRODUCT(A2:A4,B2:B4)"],
  }),
  gridLab({
    id: "logic-sumproduct-qty",
    moduleSlug: "logic",
    title: "SUMPRODUCT 네 행",
    instruction: "B6에 A2:A5와 B2:B5의 SUMPRODUCT를 구하세요.",
    difficulty: 1,
    grid: [
      ["수량", "단가"],
      [10, 2500],
      [4, 800],
      [6, 1200],
      [3, 400],
      ["합계", null],
    ],
    editable: [[5, 1]],
    validations: [
      { row: 5, col: 1, expected: 36600, re: SUMPRODUCT, msg: "36600이 맞습니다." },
    ],
    hints: ["=SUMPRODUCT(A2:A5,B2:B5)"],
  }),
  gridLab({
    id: "logic-countif",
    moduleSlug: "logic",
    title: "COUNTIF 한 조건",
    instruction: 'B6에 서울인 행 수를 COUNTIF로 구하세요.',
    difficulty: 1,
    grid: [
      ["지역", "매출"],
      ["서울", 100],
      ["부산", 80],
      ["서울", 120],
      ["서울", 50],
      ["건수", null],
    ],
    editable: [[5, 1]],
    validations: [
      { row: 5, col: 1, expected: 3, re: COUNTIF, msg: "서울 3건이 맞습니다." },
    ],
    hints: ['COUNTIF(범위, 조건)', '=COUNTIF(A2:A5,"서울")'],
  }),

  gridLab({
    id: "lookup-xlookup",
    moduleSlug: "lookup",
    title: "XLOOKUP으로 단가",
    instruction: "B6에 A200의 단가를 XLOOKUP으로 구하세요. 근사 일치는 쓰지 않습니다.",
    difficulty: 2,
    grid: [
      ["코드", "이름", "단가"],
      ["A100", "노트북", 1200],
      ["A200", "태블릿", 800],
      ["A300", "폰", 2300],
      ["조회", "A200", ""],
      ["단가", null, ""],
    ],
    editable: [[5, 1]],
    validations: [
      { row: 5, col: 1, expected: 800, re: XLOOKUP, msg: "A200 단가 800이 맞습니다." },
    ],
    hints: ["XLOOKUP(값, 조회열, 반환열)", "=XLOOKUP(B5,A2:A4,C2:C4)"],
  }),
  gridLab({
    id: "lookup-xlookup-left",
    moduleSlug: "lookup",
    title: "XLOOKUP 왼쪽 반환",
    instruction: "B6에 이름 태블릿에 해당하는 코드를 XLOOKUP으로 구하세요. 조회열이 반환열 오른쪽에 있어도 됩니다.",
    difficulty: 2,
    grid: [
      ["코드", "이름", "단가"],
      ["A100", "노트북", 1200],
      ["A200", "태블릿", 800],
      ["A300", "폰", 2300],
      ["조회", "태블릿", ""],
      ["코드", null, ""],
    ],
    editable: [[5, 1]],
    validations: [
      { row: 5, col: 1, expected: "A200", re: XLOOKUP, msg: "왼쪽 조회가 맞습니다." },
    ],
    hints: ["=XLOOKUP(B5,B2:B4,A2:A4)"],
  }),
  gridLab({
    id: "lookup-xlookup-missing",
    moduleSlug: "lookup",
    title: "XLOOKUP if_not_found",
    instruction: 'B6에 없는 코드 A999를 XLOOKUP으로 찾고, 없으면 "없음"을 네 번째 인수로 넣으세요.',
    difficulty: 2,
    grid: [
      ["코드", "이름", "단가"],
      ["A100", "노트북", 1200],
      ["A200", "태블릿", 800],
      ["A300", "폰", 2300],
      ["조회", "A999", ""],
      ["이름", null, ""],
    ],
    editable: [[5, 1]],
    validations: [
      { row: 5, col: 1, expected: "없음", re: XLOOKUP, msg: "없는 키를 if_not_found로 처리했습니다." },
    ],
    hints: ['=XLOOKUP(B5,A2:A4,B2:B4,"없음")'],
  }),
];
