import type { Module, Phase, Quiz } from "./types";

function quiz(id: string, q: string, options: string[], answer: number, explain: string): Quiz {
  return { id, q, options, answer, explain };
}

const pivotQuizzes: Quiz[] = [
  quiz(
    "pivot-q1",
    "일별 매출 데이터를 분기별로 묶으려면?",
    ["날짜 우클릭 → 그룹화 → 분기", "QUARTER 함수로 새 열", "필터에서 분기 선택", "정렬 후 소계"],
    0,
    "피벗 날짜 필드 우클릭 → 그룹화. 원본 데이터를 건드리지 않는다.",
  ),
  quiz(
    "pivot-q2",
    "피벗에서 매출 대비 원가 비율을 보려면?",
    ["옆 셀에 수식", "Calculated Field로 =원가/매출", "값 형식을 %로 변경", "조건부 서식"],
    1,
    "Calculated Field는 피벗 내부에서 필드 간 연산. 원본에 열을 추가하지 않아도 됨.",
  ),
];

const cleanQuizzes: Quiz[] = [
  quiz(
    "data-clean-q1",
    "같은 형식의 월별 시트 여러 개를 합치는 가장 효율적 방법?",
    ["수동 복사", "INDIRECT", "Power Query Append", "VBA 매크로"],
    2,
    "Append는 같은 구조의 테이블을 합친다. 새 시트가 추가돼도 새로고침 한 번.",
  ),
  quiz(
    "data-clean-q2",
    '" Samsung Electronics Co. " (앞뒤 공백)을 정리하려면?',
    ["CLEAN", "TRIM", 'SUBSTITUTE(," ","")', "LEFT"],
    1,
    "TRIM은 앞뒤 공백 + 중간 연속 공백을 하나로. SUBSTITUTE는 단어 사이도 지운다.",
  ),
];

const finQuizzes: Quiz[] = [
  quiz(
    "fin-fn-q1",
    "NPV와 XNPV의 차이는?",
    ["할인율 정확도", "NPV는 등간격, XNPV는 날짜 기반", "XNPV는 음수 처리", "차이 없음"],
    1,
    "NPV는 1기간 간격 가정. XNPV는 날짜 기반으로 불규칙 간격도 정확히 할인.",
  ),
  quiz(
    "fin-fn-q2",
    "=PMT(0.05/12, 360, -500000000)의 의미는?",
    ["5억, 연 5%, 30년 월 상환액", "5억의 5% 이자", "30년 후 미래가치", "월 5%로 적금"],
    0,
    "PMT(월이율, 기간수, 현재가치). 대출 스케줄링에서 핵심.",
  ),
  quiz(
    "fin-fn-q3",
    "이 그리드에서 XNPV 날짜를 DATE()로 두고 참조하면?",
    ["정상 계산", "#VALUE!가 날 수 있다. 일련번호를 쓴다", "XIRR과 같음", "0"],
    1,
    "HyperFormula XNPV는 날짜 일련번호(숫자)를 기대한다. XIRR은 DATE()를 받는다.",
  ),
  quiz(
    "fin-fn-q4",
    "IPMT가 계산하는 것은?",
    ["월 상환액 전체", "해당 회차의 이자분", "원금분", "잔액"],
    1,
    "IPMT는 이자, PPMT는 원금. 둘을 더하면 PMT에 가깝다.",
  ),
  quiz(
    "fin-fn-q5",
    "목표 금액에 도달하는 기간을 구하려면?",
    ["RATE", "NPER", "PV", "NPV"],
    1,
    "NPER(이율, 납입, pv, fv)가 기간을 역산한다.",
  ),
  quiz(
    "fin-fn-q6",
    "PPMT의 결과는?",
    ["이자만", "해당 회차 원금 상환분", "남은 원금", "총이자"],
    1,
    "PPMT는 그 회차에 깎이는 원금.",
  ),
  quiz(
    "fin-fn-q7",
    "대출 IPMT에서 원금을 양수로 넣고 결과도 양수로 읽으면?",
    ["항상 맞다", "부호 규칙이 뒤집힐 수 있다", "이자가 0", "NPER이 필요"],
    1,
    "PMT 계열은 유출을 음수로 두는 편이 안전하다.",
  ),
  quiz(
    "fin-fn-q8",
    "월 적립 NPER의 이율은?",
    ["연 이율 그대로", "연 이율/12", "연 이율*12", "WACC"],
    1,
    "납입이 월이면 이율도 월로 맞춘다.",
  ),
  quiz(
    "fin-fn-q9",
    "날짜 간격이 다른 현금흐름의 수익률은?",
    ["IRR", "XIRR", "RATE", "NPER"],
    1,
    "IRR은 등간격. 날짜가 있으면 XIRR.",
  ),
];

const pivot: Module = {
  id: "pivot",
  title: "피벗 테이블",
  quizzes: pivotQuizzes,
  concepts: [
    {
      id: "pivot-create",
      title: "피벗 테이블 생성 (Alt+N+V)",
      kind: "excel-only",
      why: "원본을 건드리지 않고 집계 뷰를 만든다.",
      trap: "이 그리드에는 피벗이 없다. 수식 실습은 SUMIFS 재현만.",
      ib: "실적 파일을 처음 열면 피벗으로 구조를 파악한다.",
      labIds: [],
      quizIds: ["pivot-q1"],
    },
    {
      id: "pivot-areas",
      title: "행/열/값/필터 영역",
      kind: "excel-only",
      why: "차원을 행·열에, 숫자를 값에 둔다.",
      trap: "값을 행에 넣으면 집계가 아니라 목록이 된다.",
      ib: "세그먼트×연도 매출.",
      labIds: [],
      quizIds: ["pivot-q1"],
    },
    {
      id: "pivot-value",
      title: "값 필드 설정",
      kind: "excel-only",
      why: "합계·평균·개수를 바꾼다.",
      trap: "텍스트 열을 합계로 두면 0이 된다.",
      ib: "건수와 금액을 같이 본다.",
      labIds: [],
      quizIds: ["pivot-q2"],
    },
    {
      id: "pivot-group",
      title: "날짜 그룹화",
      kind: "excel-only",
      why: "일별을 월·분기로 접는다. 원본에 열을 안 만든다.",
      trap: "빈 날짜·텍스트 날짜는 그룹이 실패한다.",
      ib: "분기 실적 피벗.",
      labIds: [],
      quizIds: ["pivot-q1"],
    },
    {
      id: "pivot-slicer",
      title: "슬라이서",
      kind: "excel-only",
      why: "필터를 버튼으로 보여 준다.",
      trap: "여러 피벗을 연결하지 않으면 슬라이서가 하나만 움직인다.",
      ib: "리뷰 파일의 시나리오 전환.",
      labIds: [],
      quizIds: ["pivot-q2"],
    },
    {
      id: "pivot-chart",
      title: "피벗 차트",
      kind: "excel-only",
      why: "피벗과 같은 캐시에 묶인 차트.",
      trap: "원본 차트가 아니라 피벗을 지으면 차트도 죽는다.",
      ib: "주간 리뷰 슬라이드.",
      labIds: [],
      quizIds: ["pivot-q2"],
    },
    {
      id: "pivot-calc",
      title: "Calculated Field",
      kind: "excel-only",
      why: "원본에 열 없이 피벗 안에서 비율을 만든다.",
      trap: "계산 필드는 합계 뒤에 나누지, 행별 비율의 합이 아니다.",
      ib: "매출 대비 원가.",
      labIds: [],
      quizIds: ["pivot-q2"],
    },
  ],
};

const dataClean: Module = {
  id: "data-clean",
  title: "데이터 정리 & PQ",
  quizzes: cleanQuizzes,
  concepts: [
    {
      id: "clean-text-to-columns",
      title: "Text to Columns",
      kind: "excel-only",
      why: "구분자로 한 열을 나눈다.",
      trap: "오른쪽 열을 덮어쓴다. 빈 열을 먼저 확보한다.",
      ib: "붙여넣은 CUSIP·티커 분리.",
      labIds: [],
      quizIds: ["data-clean-q2"],
    },
    {
      id: "clean-dedupe",
      title: "중복 제거, 빈 셀 처리",
      kind: "excel-only",
      why: "키 중복과 빈 행을 원본에서 뺀다.",
      trap: "중복 제거는 첫 행만 남긴다. 어느 행이 맞는지만 확인하고 돌린다.",
      ib: "거래 목록 클린업.",
      labIds: [],
      quizIds: ["data-clean-q1"],
    },
    {
      id: "clean-trim",
      title: "TRIM, CLEAN, SUBSTITUTE",
      kind: "grid",
      why: "공백·제어문자·접미어를 수식으로 정리한다.",
      syntax: "TRIM(text) / SUBSTITUTE(text, old, new)",
      trap: "모든 공백을 지우려면 SUBSTITUTE. TRIM은 단어 사이 하나를 남긴다.",
      ib: "외부에서 받은 회사명 정규화.",
      labIds: ["clean-trim", "clean-substitute"],
      quizIds: ["data-clean-q2"],
    },
    {
      id: "clean-extract",
      title: "LEFT, RIGHT, MID, FIND, LEN",
      kind: "grid",
      why: "코드에서 필요한 조각만 잘라 키로 쓴다.",
      syntax: "LEFT/MID/RIGHT + FIND",
      trap: "FIND는 대소문자를 가린다. 구분자가 없으면 #VALUE!.",
      ib: "티커-연도-시퀀스 코드 분해.",
      labIds: ["clean-extract"],
      quizIds: ["data-clean-q2"],
    },
    {
      id: "clean-pq",
      title: "Power Query 기초",
      kind: "excel-only",
      why: "반복 정리를 쿼리로 남긴다. 이 그리드에는 PQ가 없다.",
      trap: "시트를 수동으로 고치면 새로고침이 덮어쓴다.",
      ib: "월별 파일을 한 테이블로.",
      labIds: [],
      quizIds: ["data-clean-q1"],
    },
    {
      id: "clean-unpivot",
      title: "열 병합/분할, 피벗 해제",
      kind: "excel-only",
      why: "넓은 연도 열을 긴 테이블로 바꾼다.",
      trap: "헤더가 값이 아니면 Unpivot이 의미를 잃는다.",
      ib: "연도별 가로 실적 → 세로 시계열.",
      labIds: [],
      quizIds: ["data-clean-q1"],
    },
    {
      id: "clean-merge-append",
      title: "Merge & Append",
      kind: "excel-only",
      why: "같은 구조는 Append, 키로 붙이려면 Merge.",
      trap: "열 이름이 다르면 Append가 새 열을 만든다.",
      ib: "월별 시트를 쌓기.",
      labIds: [],
      quizIds: ["data-clean-q1"],
    },
  ],
};

const finFn: Module = {
  id: "fin-fn",
  title: "재무 함수",
  quizzes: finQuizzes,
  concepts: [
    {
      id: "fin-npv",
      title: "NPV, XNPV",
      kind: "grid",
      why: "현금흐름을 할인한다. 날짜가 불규칙하면 XNPV.",
      syntax: "NPV(rate, values…) / XNPV(rate, values, dates)",
      trap: "Excel NPV는 첫 값부터 한 기간 뒤다. t0 유출은 밖에 더한다.",
      ib: "프로젝트 평가, 간이 DCF.",
      labIds: ["fin-npv", "fin-xnpv", "fin-xnpv-uneven", "fin-xnpv-12"],
      quizIds: ["fin-fn-q1", "fin-fn-q3"],
    },
    {
      id: "fin-irr",
      title: "IRR, XIRR",
      kind: "grid",
      why: "NPV=0인 수익률. 날짜가 불규칙하면 XIRR.",
      syntax: "IRR(values) / XIRR(values, dates)",
      trap: "부호가 한 번만 바뀌지 않으면 해가 여러 개다.",
      ib: "딜 IRR, 펀드 IRR.",
      labIds: ["fin-irr", "fin-xirr", "fin-xirr-uneven"],
      quizIds: ["fin-fn-q1", "fin-fn-q9"],
    },
    {
      id: "fin-pmt",
      title: "PMT, IPMT, PPMT",
      kind: "grid",
      why: "대출 월 상환액과 이자/원금 분해.",
      syntax: "PMT(rate, nper, pv)",
      trap: "연 이율을 월로 나누고 기간도 월로 맞춘다.",
      ib: "부채 스케줄.",
      labIds: ["fin-pmt", "fin-ipmt", "fin-ipmt-12", "fin-ipmt-last", "fin-ppmt", "fin-ppmt-12"],
      quizIds: ["fin-fn-q2", "fin-fn-q4", "fin-fn-q6"],
    },
    {
      id: "fin-pvfv",
      title: "PV, FV",
      kind: "grid",
      why: "현재가치와 미래가치.",
      syntax: "PV(rate, nper, pmt, [fv]) / FV(rate, nper, pmt, [pv])",
      trap: "부호 규칙: 유출은 음수.",
      ib: "목표 적립, 채권 간이 PV.",
      labIds: ["fin-pvfv"],
      quizIds: ["fin-fn-q2"],
    },
    {
      id: "fin-rate",
      title: "RATE, NPER",
      kind: "grid",
      why: "이율 또는 기간을 역산한다.",
      syntax: "RATE(nper, pmt, pv, [fv])",
      trap: "guess가 없으면 수렴 실패할 수 있다.",
      ib: "내재 수익률 역산.",
      labIds: ["fin-rate", "fin-nper", "fin-nper-pmt"],
      quizIds: ["fin-fn-q2", "fin-fn-q5", "fin-fn-q8"],
    },
    {
      id: "fin-sign",
      title: "부호 규칙 (유입=+, 유출=-)",
      kind: "grid",
      why: "PMT/PV/FV는 방향이 반대면 부호가 반대다.",
      trap: "대출 원금을 양수로 넣고 PMT도 양수로 두면 의미가 뒤집힌다.",
      ib: "은행 관점 vs 차주 관점을 한 모델에서 섞지 않는다.",
      labIds: ["fin-pmt", "fin-ipmt"],
      quizIds: ["fin-fn-q2", "fin-fn-q7"],
    },
  ],
};

export const PHASE2: Phase = {
  phase: 2,
  title: "재무 분석 실무",
  weeks: "3–4주차",
  desc: "피벗 테이블, 데이터 정리, 재무 함수",
  modules: [pivot, dataClean, finFn],
};
