import type { Module, Phase, Quiz } from "./types";

function quiz(id: string, q: string, options: string[], answer: number, explain: string): Quiz {
  return { id, q, options, answer, explain };
}

const modelQuizzes: Quiz[] = [
  quiz(
    "model-structure-q1",
    "성장률 15%를 =B5*1.15로 직접 쓰면 안 되는 이유는?",
    ["계산이 느림", "가정 변경 시 모든 셀을 수정해야 함", "에러 발생", "서식 깨짐"],
    1,
    "하드코딩은 감사 불가능 + 시나리오 변경 시 누락. Assumptions에서 참조해야.",
  ),
  quiz(
    "model-structure-q2",
    "BS 밸런스 체크 행(자산-부채-자본=0)을 넣는 이유는?",
    ["보기 좋아서", "에러를 즉시 감지하기 위해", "엑셀 기능상 필수", "인쇄용"],
    1,
    "밸런스 안 맞으면 IS→BS→CF 연결 오류 신호. 역추적해서 버그 찾는다.",
  ),
];

const stmtQuizzes: Quiz[] = [
  quiz(
    "three-stmt-q1",
    "간접법 CF에서 감가상각비를 순이익에 더하는 이유는?",
    ["비용이 아님", "IS에서 차감됐지만 현금유출이 아니라서", "BS 밸런스 맞추기", "세금 절감"],
    1,
    "감가상각은 IS에서 빠졌지만 현금은 Capex 시점에 나감. CF에서 복원한다.",
  ),
  quiz(
    "three-stmt-q2",
    "매출채권 증가가 영업CF에 미치는 영향은?",
    ["CF 증가", "CF 감소", "영향 없음", "투자활동에 반영"],
    1,
    "매출채권↑ = 매출 인식됐지만 현금 미수취. CF에서 차감.",
  ),
];

const dcfQuizzes: Quiz[] = [
  quiz(
    "dcf-intro-q1",
    "TV가 기업가치의 60–80%를 차지한다. 이것이 의미하는 바는?",
    [
      "예측 기간 CF는 중요하지 않다",
      "TV 가정에 대한 감도분석이 필수다",
      "DCF는 신뢰할 수 없다",
      "예측 기간을 늘려야 한다",
    ],
    1,
    "TV 비중이 크면 성장률/할인율의 작은 변화가 밸류에이션을 크게 흔든다.",
  ),
  quiz(
    "dcf-intro-q2",
    "EV에서 Equity Value를 구하려면?",
    ["EV + 순차입금", "EV - 순차입금", "EV × 주식수", "EV / WACC"],
    1,
    "Equity = EV - Net Debt. EV는 채권자+주주 전체, 빚을 빼면 주주 몫.",
  ),
];

const model: Module = {
  id: "model-structure",
  title: "모델 설계 원칙",
  quizzes: modelQuizzes,
  concepts: [
    {
      id: "model-color",
      title: "컬러 컨벤션: 입력=파랑, 수식=검정, 링크=초록",
      kind: "excel-only",
      why: "누가 고쳐도 입력을 바로 찾는다.",
      trap: "서식만 파랑이고 값이 수식이면 감사가 거짓말이다.",
      ib: "Macabacus·팀 표준.",
      labIds: [],
      quizIds: ["model-structure-q1"],
    },
    {
      id: "model-no-hardcode",
      title: "하드코딩 금지",
      kind: "grid",
      why: "가정은 한곳에만 둔다. 본문은 참조만 한다.",
      trap: "수식 안의 1.15는 성장률이 아니다. 숨은 가정이다.",
      ib: "시나리오 스위치의 전제.",
      labIds: ["model-assumptions"],
      quizIds: ["model-structure-q1"],
    },
    {
      id: "model-sheets",
      title: "시트 구조: Assumptions → IS → BS → CF → Valuation",
      kind: "excel-only",
      why: "흐름이 한 방향이면 순환을 찾기 쉽다. 이 그리드는 단일 시트다.",
      trap: "시트를 건너뛰는 링크는 추적이 어렵다.",
      ib: "표준 5탭.",
      labIds: [],
      quizIds: ["model-structure-q1"],
    },
    {
      id: "model-bs-check",
      title: "BS 밸런스 체크 행",
      kind: "grid",
      why: "자산-부채-자본이 0이 아니면 연결이 깨진 것이다.",
      trap: "반올림 오차와 진짜 에러를 나눌 허용 오차를 둔다.",
      ib: "모든 출력 시트 상단에 체크.",
      labIds: ["model-balance-check"],
      quizIds: ["model-structure-q2"],
    },
    {
      id: "model-scenario",
      title: "시나리오 스위치",
      kind: "excel-only",
      why: "Base/Upside/Downside를 한 칸으로 고른다.",
      trap: "스위치가 가리키지 않는 가정이 본문에 남아 있으면 가짜 시나리오다.",
      ib: "IC 자료의 케이스 전환.",
      labIds: [],
      quizIds: ["model-structure-q1"],
    },
    {
      id: "model-circ",
      title: "순환참조 해결",
      kind: "excel-only",
      why: "이자↔차입금은 순환이다. 이 엔진은 순환을 풀지 않는다.",
      trap: "반복 계산을 켜면 숨은 순환이 조용히 수렴한다. 위치를 표시해야 한다.",
      ib: "리볼버 플러그, 이자.",
      labIds: [],
      quizIds: ["model-structure-q2"],
    },
  ],
};

const threeStmt: Module = {
  id: "three-stmt",
  title: "3-Statement 연결",
  quizzes: stmtQuizzes,
  concepts: [
    {
      id: "stmt-is",
      title: "IS 구축",
      kind: "grid",
      why: "매출→비용→세후 순이익. 아래 연결의 출발점.",
      trap: "세율을 수식에 하드코딩하지 않는다.",
      ib: "P&L 골격.",
      labIds: ["stmt-net-income"],
      quizIds: ["three-stmt-q1"],
    },
    {
      id: "stmt-bs",
      title: "BS 구축",
      kind: "excel-only",
      why: "자산=부채+자본. 전체 표는 엑셀 템플릿에서 연습한다.",
      trap: "현금은 CF 결과가 들어와야 닫힌다.",
      ib: "연말 잔액.",
      labIds: [],
      quizIds: ["three-stmt-q2"],
    },
    {
      id: "stmt-cf",
      title: "CF 간접법",
      kind: "grid",
      why: "순이익에서 시작해 비현금·WC·투자·재무를 조정한다.",
      trap: "감가상각을 빼면 현금이 두 번 나간다.",
      ib: "CFO 표준.",
      labIds: ["stmt-cf-addback"],
      quizIds: ["three-stmt-q1"],
    },
    {
      id: "stmt-is-bs",
      title: "IS→BS: 순이익→이익잉여금",
      kind: "grid",
      why: "당기순이익이 RE를 밀어 올린다.",
      trap: "배당을 빼지 않으면 RE가 과대하다.",
      ib: "연결의 첫 고리.",
      labIds: ["stmt-net-income"],
      quizIds: ["three-stmt-q1"],
    },
    {
      id: "stmt-bs-cf",
      title: "BS→CF: 운전자본 변동, 감가상각",
      kind: "grid",
      why: "자산 증가는 현금 사용, DA는 가산.",
      trap: "증감을 기말-기초 방향으로 통일한다.",
      ib: "WC 브리지.",
      labIds: ["stmt-working-cap", "stmt-cf-addback"],
      quizIds: ["three-stmt-q2"],
    },
    {
      id: "stmt-cf-bs",
      title: "CF→BS: 기말 현금",
      kind: "excel-only",
      why: "CF의 기말 현금이 BS 현금이다. 단일 시트 실습에는 넣지 않는다.",
      trap: "직접 숫자를 넣으면 순환이 숨는다.",
      ib: "밸런스가 안 맞으면 현금을 의심한다.",
      labIds: [],
      quizIds: ["three-stmt-q2"],
    },
    {
      id: "stmt-circ-interest",
      title: "순환참조: 이자비용↔차입금",
      kind: "excel-only",
      why: "평균 차입금×이율은 순환이다. 그리드에서 풀지 않는다.",
      trap: "기초 잔액만 쓰면 순환은 사라지지만 부정확하다.",
      ib: "리볼버 모델.",
      labIds: [],
      quizIds: ["three-stmt-q1"],
    },
  ],
};

const dcf: Module = {
  id: "dcf-intro",
  title: "DCF 기초",
  quizzes: dcfQuizzes,
  concepts: [
    {
      id: "dcf-fcf",
      title: "FCF = 영업CF - Capex",
      kind: "grid",
      why: "기업에 남는 현금을 할인한다.",
      trap: "이자·순차입 변동을 FCF에 넣으면 Equity/Enterprise가 섞인다.",
      ib: "UFCF vs LFCF를 명시한다.",
      labIds: ["dcf-fcf", "dcf-discount"],
      quizIds: ["dcf-intro-q1"],
    },
    {
      id: "dcf-wacc",
      title: "WACC",
      kind: "excel-only",
      why: "영업 현금의 할인율. 실습 수식은 다음이 아니라 개념+퀴즈.",
      trap: "목표 자본구조와 현재 구조를 섞지 않는다.",
      ib: "할인율 한 칸은 가정 시트.",
      labIds: [],
      quizIds: ["dcf-intro-q1"],
    },
    {
      id: "dcf-tv",
      title: "Terminal Value",
      kind: "excel-only",
      why: "예측 구간 이후 가치를 한 숫자로 접는다.",
      trap: "성장률 ≥ WACC면 폭발한다.",
      ib: "Exit multiple과 Gordon을 병행.",
      labIds: [],
      quizIds: ["dcf-intro-q1"],
    },
    {
      id: "dcf-bridge",
      title: "EV → Equity Value",
      kind: "grid",
      why: "기업가치에서 순차입금을 빼 주주 몫을 구한다.",
      syntax: "Equity = EV - Net Debt",
      trap: "현금을 두 번 빼거나 소수주주를 빠뜨린다.",
      ib: "Football field의 다리.",
      labIds: ["dcf-ev-equity"],
      quizIds: ["dcf-intro-q2"],
    },
    {
      id: "dcf-dt",
      title: "감도분석 Data Table",
      kind: "excel-only",
      why: "WACC×성장률 격자를 엑셀 Data Table로 만든다. 이 그리드에는 없다.",
      trap: "테이블이 가리키는 출력 셀이 바뀌면 격자가 죽는다.",
      ib: "IC 부록.",
      labIds: [],
      quizIds: ["dcf-intro-q1"],
    },
    {
      id: "dcf-ff",
      title: "Football Field Chart",
      kind: "excel-only",
      why: "방법론별 가치 범위를 한 그림으로.",
      trap: "축 단위(주당 vs EV)를 섞으면 비교가 가짜다.",
      ib: "밸류에이션 요약 슬라이드.",
      labIds: [],
      quizIds: ["dcf-intro-q2"],
    },
  ],
};

export const PHASE3: Phase = {
  phase: 3,
  title: "재무 모델링 기초",
  weeks: "5–8주차",
  desc: "3-Statement Model + DCF",
  practiceFile: { name: "phase3-model-template.xlsx", href: "/learn/phase3-model-template.xlsx" },
  modules: [model, threeStmt, dcf],
};
