import type { Module, Phase, Quiz } from "./types";

function quiz(id: string, q: string, options: string[], answer: number, explain: string): Quiz {
  return { id, q, options, answer, explain };
}

const navQuizzes: Quiz[] = [
  quiz(
    "nav-q1",
    "1000행 데이터에서 A1에서 마지막 데이터 행까지 이동하려면?",
    ["Ctrl+End", "Ctrl+↓", "Ctrl+Shift+End", "Page Down"],
    1,
    "Ctrl+↓는 현재 열에서 데이터가 있는 마지막 셀까지 점프한다. Ctrl+End는 사용된 범위의 우하단 끝으로 간다.",
  ),
  quiz(
    "nav-q2",
    "A1:A500을 한 번에 선택하는 가장 빠른 방법은?",
    ["드래그", "Ctrl+Shift+↓", "Shift+Ctrl+End", "이름 상자에 A1:A500 입력"],
    1,
    "A1에서 Ctrl+Shift+↓. 데이터가 연속이면 마지막 행까지 선택된다.",
  ),
  quiz(
    "nav-q3",
    "셀 서식 대화상자를 여는 단축키는?",
    ["Ctrl+F", "Ctrl+1", "Ctrl+Shift+1", "Alt+H"],
    1,
    "Ctrl+1이 셀 서식(Format Cells) 대화상자. Ctrl+Shift+1은 숫자 서식을 바로 적용한다.",
  ),
];

const basicQuizzes: Quiz[] = [
  quiz(
    "basic-fn-q1",
    "B2에 =A2*C$1 수식이 있다. B3로 복사하면?",
    ["=A3*C$1", "=A2*C$1", "=A3*C$2", "=A2*C$2"],
    0,
    "A2→A3 (상대참조), C$1→C$1 (혼합참조, $가 행 고정). 세율 같은 고정 값 참조에 쓰는 패턴.",
  ),
  quiz(
    "basic-fn-q2",
    "빈 셀 제외하고 데이터가 있는 셀 수를 세려면?",
    ["COUNT", "COUNTA", "COUNTBLANK", "LEN"],
    1,
    "COUNT는 숫자만, COUNTA는 비어있지 않은 셀 전부, COUNTBLANK는 빈 셀.",
  ),
  quiz(
    "basic-fn-q3",
    "두 번째로 큰 값을 구하려면?",
    ["MAX-1", "LARGE(범위, 2)", "RANK(2)", "INDEX(MAX)"],
    1,
    "LARGE(범위, k)는 k번째로 큰 값. SMALL은 반대.",
  ),
  quiz(
    "basic-fn-q4",
    "빈 셀 개수만 세려면?",
    ["COUNTA", "COUNTBLANK", "COUNT", "LEN"],
    1,
    "COUNTBLANK는 빈 셀. COUNT는 숫자, COUNTA는 비어 있지 않은 셀.",
  ),
  quiz(
    "basic-fn-q5",
    "세 번째로 작은 값을 구하려면?",
    ["MIN-2", "SMALL(범위, 3)", "LARGE(범위, 3)", "RANK(3)"],
    1,
    "SMALL(범위, k)는 k번째로 작은 값. LARGE는 큰 쪽.",
  ),
  quiz(
    "basic-fn-q6",
    "숫자 3개와 빈 칸 1개가 있는 범위에서 COUNT와 COUNTBLANK는?",
    ["3과 1", "4와 1", "3과 0", "4와 0"],
    0,
    "COUNT는 숫자만 3, COUNTBLANK는 빈 칸 1.",
  ),
  quiz(
    "basic-fn-q7",
    "LARGE(범위,1)과 같은 결과는?",
    ["SMALL(범위,1)", "MAX(범위)", "MIN(범위)", "AVERAGE(범위)"],
    1,
    "LARGE(...,1)은 최댓값이라 MAX와 같다.",
  ),
  quiz(
    "basic-fn-q8",
    "한 열에서 최댓값만 필요하면?",
    ["LARGE(범위, 1)", "MAX(범위)가 더 짧다", "RANK", "둘 다 불가"],
    1,
    "최댓값만이면 MAX. LARGE는 k번째가 필요할 때.",
  ),
];

const logicQuizzes: Quiz[] = [
  quiz(
    "logic-q1",
    '매출 1억 이상 + 지역 "서울"인 행의 합계를 구하려면?',
    ['SUMIF(지역,"서울",매출)', 'SUMIFS(매출,지역,"서울",매출,">="&1억)', "SUM(IF(...))", "SUMPRODUCT"],
    1,
    "SUMIFS는 복수 조건. 첫 인수가 합산 범위, 이후 (조건범위, 조건) 쌍을 나열.",
  ),
  quiz(
    "logic-q2",
    "VLOOKUP에서 #N/A 대신 0을 표시하려면?",
    ["IF(VLOOKUP=NA,0)", "IFERROR(VLOOKUP(...), 0)", "VLOOKUP(..., FALSE, 0)", "ISNA(VLOOKUP(...))"],
    1,
    "IFERROR는 에러 시 지정한 값으로 대체. 재무 모델에서 필수.",
  ),
  quiz(
    "logic-q3",
    '=IF(AND(A1>100, B1="Y"), "승인", "보류") — A1=150, B1="N"일 때?',
    ["승인", "보류", "#VALUE!", "TRUE"],
    1,
    'AND는 모든 조건이 TRUE여야 함. B1="N"이므로 FALSE → "보류".',
  ),
  quiz(
    "logic-q4",
    "OR는 언제 TRUE인가?",
    ["모든 조건이 TRUE", "하나라도 TRUE", "모두 FALSE", "숫자만"],
    1,
    "OR는 조건 중 하나만 참이면 참.",
  ),
  quiz(
    "logic-q5",
    "이 그리드에서 IFS의 마지막 분기에 TRUE를 쓰면?",
    ["그 외 전부", "#NAME?", "0", "FALSE"],
    1,
    "HyperFormula는 TRUE를 이름로 본다. B2>=0처럼 비교를 쓴다.",
  ),
  quiz(
    "logic-q6",
    "IFNA가 IFERROR와 다른 점은?",
    ["더 빠르다", "#N/A만 대체하고 #DIV/0!는 남긴다", "배열만 받는다", "차이 없음"],
    1,
    "조회 실패만 가릴 때 IFNA. IFERROR는 모든 에러를 삼킨다.",
  ),
  quiz(
    "logic-q7",
    "이 실습 그리드에서 AVERAGEIFS를 치면?",
    ["조건 평균", "#NAME?", "AVERAGEIF와 동일", "0"],
    1,
    "AVERAGEIFS는 엔진에 없다. AVERAGEIF만 계산한다.",
  ),
  quiz(
    "logic-q8",
    "이 엔진에서 SUMPRODUCT((A1:A4=\"서울\")*(C1:C4))는?",
    ["서울 합계", "#VALUE! (배열 조건 불가)", "0", "TRUE"],
    1,
    "수량×단가처럼 숫자 배열만 곱해 더한다. 조건 배열은 엑셀 365에서.",
  ),
  quiz(
    "logic-q9",
    "SUMIFS의 첫 인수는?",
    ["조건 범위", "합산 범위", "조건", "평균 범위"],
    1,
    "SUMIFS는 합산 범위가 먼저다. SUMIF와 순서가 반대.",
  ),
  quiz(
    "logic-q10",
    "NOT(A1>10)이 TRUE인 경우는?",
    ["A1=20", "A1=5", "A1=10.1", "A1이 텍스트"],
    1,
    "NOT은 조건을 뒤집는다. 5>10은 FALSE → NOT은 TRUE.",
  ),
  quiz(
    "logic-q11",
    "한 조건으로 행 수를 세는 함수는?",
    ["COUNTIFS만", "COUNTIF", "COUNTA", "COUNTBLANK"],
    1,
    "조건 하나면 COUNTIF. 둘 이상이면 COUNTIFS.",
  ),
  quiz(
    "logic-q12",
    "IFS에서 어떤 조건도 참이 아니면?",
    ["0", "#N/A", "마지막 값", "FALSE"],
    1,
    "짝이 맞는 참이 없으면 #N/A. 그래서 마지막에 항상 참인 비교를 둔다.",
  ),
];

const lookupQuizzes: Quiz[] = [
  quiz(
    "lookup-q1",
    "INDEX-MATCH가 VLOOKUP보다 선호되는 핵심 이유는?",
    ["더 빠르다", "조회 열이 왼쪽에 있어도 작동한다", "자동 에러 처리", "피벗 호환"],
    1,
    "VLOOKUP은 왼→오 고정. INDEX-MATCH는 방향 제한 없고 열 삽입에 안전.",
  ),
  quiz(
    "lookup-q2",
    "MATCH의 세 번째 인수 0의 의미는?",
    ["오름차순 근사", "정확 일치", "내림차순 근사", "와일드카드"],
    1,
    "0은 exact match. 재무 데이터에서는 거의 항상 0.",
  ),
  quiz(
    "lookup-q3",
    "특정 회사의 특정 연도 매출을 동적으로 찾을 때 쓰는 패턴은?",
    ["VLOOKUP 중첩", "INDEX-MATCH-MATCH", "INDIRECT", "OFFSET"],
    1,
    "INDEX(데이터, MATCH(행값,행헤더,0), MATCH(열값,열헤더,0)). 모델링 핵심 패턴.",
  ),
  quiz(
    "lookup-q4",
    "XLOOKUP이 VLOOKUP보다 나은 핵심은?",
    ["더 짧은 이름", "조회열 위치 제한이 없다", "피벗이 필요", "근사만 된다"],
    1,
    "반환열을 따로 지정하므로 왼쪽 조회가 된다.",
  ),
  quiz(
    "lookup-q5",
    "XLOOKUP에서 키가 없을 때 0을 주려면?",
    ["IFERROR만", "네 번째 인수 if_not_found", "FALSE", "MATCH -1"],
    1,
    "XLOOKUP(값, 조회, 반환, 0)처럼 if_not_found를 넣는다.",
  ),
  quiz(
    "lookup-q6",
    "이름에서 코드를 찾으려면 XLOOKUP의 조회 배열은?",
    ["코드 열", "이름 열", "단가 열", "시트 전체"],
    1,
    "찾는 값이 있는 열이 조회 배열, 주고 싶은 열이 반환 배열.",
  ),
  quiz(
    "lookup-q7",
    "재무 조회에서 XLOOKUP 기본 일치 방식은?",
    ["근사", "정확 일치", "와일드카드", "정규식"],
    1,
    "기본이 정확 일치다. 근사를 켜지 않는다.",
  ),
  quiz(
    "lookup-q8",
    "이 그리드의 VLOOKUP·XLOOKUP에서 FALSE를 쓰면?",
    ["정확 일치", "#NAME?", "0과 같음", "TRUE"],
    1,
    "FALSE는 이름이 아니다. 정확 일치는 0.",
  ),
];

const nav: Module = {
  id: "nav",
  title: "네비게이션 & 단축키",
  quizzes: navQuizzes,
  concepts: [
    {
      id: "nav-ctrl-arrow",
      title: "Ctrl+방향키로 데이터 끝까지 이동",
      kind: "excel-only",
      why: "큰 테이블에서 스크롤 대신 점프해야 속도가 나온다.",
      trap: "Ctrl+End는 사용된 범위의 우하단이다. 빈 서식 때문에 엉뚱한 곳으로 간다.",
      ib: "모델에서 가정 블록·출력 블록 사이를 왕복할 때 기본 이동이다.",
      labIds: [],
      xlsxTaskId: "hands",
      quizIds: ["nav-q1"],
    },
    {
      id: "nav-ctrl-shift",
      title: "Ctrl+Shift+방향키로 범위 선택",
      kind: "excel-only",
      why: "연속 데이터를 한 번에 잡아 SUM이나 서식을 건다.",
      trap: "중간에 빈 칸이 있으면 거기서 멈춘다.",
      ib: "열 전체를 잡아 붙여넣기·서식 복사할 때 쓴다.",
      labIds: [],
      xlsxTaskId: "hands",
      quizIds: ["nav-q2"],
    },
    {
      id: "nav-space",
      title: "Ctrl+Space / Shift+Space (열/행 선택)",
      kind: "excel-only",
      why: "열 숨기기·행 삽입 전에 범위를 정확히 잡는다.",
      trap: "표(Table) 안에서는 표 열만 선택될 수 있다.",
      ib: "입력 열을 숨기거나 체크 행을 넣을 때 쓴다.",
      labIds: [],
      xlsxTaskId: "hands",
      quizIds: ["nav-q2"],
    },
    {
      id: "nav-alt-ribbon",
      title: "Alt → 리본 단축키 체계",
      kind: "excel-only",
      why: "마우스로 리본을 헤매지 않고 피벗·서식에 들어간다.",
      trap: "언어 팩에 따라 키가 다르다. 영문 Excel 기준을 기억한다.",
      ib: "피벗은 Alt+N+V가 기본이다.",
      labIds: [],
      xlsxTaskId: "hands",
      quizIds: ["nav-q3"],
    },
    {
      id: "nav-f2",
      title: "F2 (셀 편집 모드 진입)",
      kind: "excel-only",
      why: "수식을 고칠 때 더블클릭 대신 키보드로 들어간다.",
      trap: "편집 모드에서 방향키는 셀 이동이 아니라 수식 안 이동이다.",
      ib: "감사 중 수식을 읽을 때 F2로 참조를 색으로 확인한다.",
      labIds: [],
      xlsxTaskId: "hands",
      quizIds: ["nav-q3"],
    },
    {
      id: "nav-format",
      title: "Ctrl+1 (셀 서식), Ctrl+; (오늘 날짜)",
      kind: "excel-only",
      why: "숫자·날짜 서식을 대화상자로 고정한다.",
      trap: "Ctrl+Shift+1은 서식 상자가 아니라 즉시 숫자 서식이다.",
      ib: "입력 셀은 파랑, 단위는 서식으로 분리한다.",
      labIds: [],
      xlsxTaskId: "hands",
      quizIds: ["nav-q3"],
    },
    {
      id: "nav-fill-keys",
      title: "Ctrl+D / Ctrl+R (아래/오른쪽 채우기)",
      kind: "excel-only",
      why: "한 칸 수식을 범위로 복제한다. 상대참조가 밀린다.",
      trap: "이 그리드의 채우기는 모서리 핸들만 있다. 단축키는 엑셀에서 연습한다.",
      ib: "열을 내린 뒤 가정 셀은 $로 잠근다.",
      labIds: [],
      xlsxTaskId: "hands",
      quizIds: ["nav-q1"],
    },
  ],
};

const basicFn: Module = {
  id: "basic-fn",
  title: "기본 함수",
  quizzes: basicQuizzes,
  concepts: [
    {
      id: "basic-fn-aggregate",
      title: "SUM, AVERAGE, COUNT, COUNTA, COUNTBLANK",
      kind: "grid",
      why: "범위 집계가 모델의 첫 검증이다. 값을 더하지 말고 함수로 묶는다.",
      syntax: "SUM(range) / AVERAGE(range) / COUNT(range)",
      trap: "COUNT는 숫자만. 텍스트 라벨은 COUNTA. 빈 칸은 COUNTBLANK.",
      ib: "합계 행은 항상 SUM. 숫자를 직접 쓰면 감사가 불가능하다.",
      labIds: ["basic-fn-sum", "basic-fn-average", "basic-fn-count", "basic-fn-countblank", "basic-fn-countblank-mixed"],
      quizIds: ["basic-fn-q2", "basic-fn-q4", "basic-fn-q6", "basic-fn-q8"],
    },
    {
      id: "basic-fn-rank",
      title: "MIN, MAX, LARGE, SMALL",
      kind: "grid",
      why: "상위/하위 k개를 뽑을 때 MAX-1 같은 편법은 중복 값에서 깨진다.",
      syntax: "LARGE(array, k) / SMALL(array, k)",
      trap: "k가 범위 길이보다 크면 #NUM!.",
      ib: "민감도에서 최악·차악 시나리오를 고를 때 쓴다.",
      labIds: ["basic-fn-large", "basic-fn-min", "basic-fn-max", "basic-fn-small", "basic-fn-small-k3"],
      quizIds: ["basic-fn-q3", "basic-fn-q5", "basic-fn-q7"],
    },
    {
      id: "basic-fn-refs",
      title: "절대참조($A$1) vs 상대참조(A1) vs 혼합참조",
      kind: "grid",
      why: "채우기 핸들로 수식을 밀 때 $가 무엇을 잠그는지가 전부다.",
      syntax: "A1 상대 / $A$1 절대 / A$1·$A1 혼합",
      trap: "세율·WACC처럼 한 칸만 쓰는 값은 반드시 $.",
      ib: "가정 시트 링크는 보통 절대참조.",
      labIds: ["basic-fn-mixed-ref"],
      quizIds: ["basic-fn-q1"],
    },
    {
      id: "basic-fn-names",
      title: "이름 정의(Name Manager)로 범위에 이름 붙이기",
      kind: "excel-only",
      why: "TaxRate처럼 이름을 붙이면 수식이 읽힌다.",
      trap: "이름 범위가 밀리면 전체가 틀린다. 테이블 열 이름을 우선한다.",
      ib: "가정 블록에 이름을 붙이는 팀은 있고, 셀 주소만 쓰는 팀도 있다.",
      labIds: [],
      xlsxTaskId: "hands",
      quizIds: ["basic-fn-q1"],
    },
  ],
};

const logic: Module = {
  id: "logic",
  title: "논리 & 조건부 집계",
  quizzes: logicQuizzes,
  concepts: [
    {
      id: "logic-if",
      title: "IF / IFS / 중첩 IF",
      kind: "grid",
      why: "등급·플래그를 수식으로 고정한다.",
      syntax: 'IF(test, true, false) / IFS(test1, v1, test2, v2, …)',
      trap: "중첩이 3단을 넘으면 IFS나 룩업 테이블이 낫다.",
      ib: "코브넌트 통과 여부, 시나리오 라벨에 쓴다.",
      labIds: ["logic-if", "logic-nested-if", "logic-ifs", "logic-ifs-flag", "logic-ifs-pass"],
      quizIds: ["logic-q3", "logic-q5", "logic-q12"],
    },
    {
      id: "logic-and-or",
      title: "AND, OR, NOT",
      kind: "grid",
      why: "IF 하나에 조건을 여러 개 넣는다.",
      syntax: "AND(a, b) / OR(a, b) / NOT(a)",
      trap: "AND는 모두 참. 하나라도 거짓이면 전체가 거짓.",
      ib: "승인 게이트(실적 and 지역) 패턴.",
      labIds: ["logic-and", "logic-or", "logic-and-or", "logic-not", "logic-and-3", "logic-or-3"],
      quizIds: ["logic-q3", "logic-q4", "logic-q10"],
    },
    {
      id: "logic-iferror",
      title: "IFERROR, IFNA",
      kind: "grid",
      why: "조회 실패가 모델 전체를 #N/A로 물들이지 않게 한다.",
      syntax: "IFERROR(value, fallback)",
      trap: "IFERROR는 #DIV/0!도 삼킨다. 조회만 가리려면 IFNA.",
      ib: "룩업 열의 기본값 0 또는 n.a.",
      labIds: ["logic-iferror", "logic-ifna", "logic-ifna-hit"],
      quizIds: ["logic-q2", "logic-q6"],
    },
    {
      id: "logic-sumif",
      title: "SUMIF, SUMIFS",
      kind: "grid",
      why: "피벗 없이 조건부 합계를 수식으로 남긴다.",
      syntax: "SUMIF(range, criteria, [sum_range]) / SUMIFS(sum_range, r1, c1, …)",
      trap: "SUMIFS는 합산 범위가 첫 인수. SUMIF와 순서가 반대다.",
      ib: "세그먼트별 매출을 가정 옆에 붙일 때.",
      labIds: ["logic-sumif", "logic-sumifs", "logic-sumifs-3", "logic-sumifs-gte", "logic-sumproduct", "logic-sumproduct-qty"],
      quizIds: ["logic-q1", "logic-q8", "logic-q9"],
    },
    {
      id: "logic-countif",
      title: "COUNTIF, COUNTIFS",
      kind: "grid",
      why: "조건에 맞는 행 수를 센다.",
      syntax: "COUNTIFS(range1, criteria1, …)",
      trap: "와일드카드 * ? 를 쓰면 의도치 않은 행이 들어간다.",
      ib: "커버리지 체크(조건 충족 건수).",
      labIds: ["logic-countifs", "logic-countif"],
      quizIds: ["logic-q1", "logic-q11"],
    },
    {
      id: "logic-averageif",
      title: "AVERAGEIF, AVERAGEIFS",
      kind: "grid",
      why: "조건 평균. AVERAGEIFS는 이 엔진에 없어 엑셀에서만 확인한다.",
      syntax: "AVERAGEIF(range, criteria, [average_range])",
      trap: "이 그리드는 AVERAGEIFS를 계산하지 않는다. AVERAGEIF만 실습한다.",
      ib: "세그먼트 마진 평균.",
      labIds: ["logic-averageif", "logic-averageif-gte"],
      quizIds: ["logic-q1", "logic-q7"],
    },
  ],
};

const lookup: Module = {
  id: "lookup",
  title: "INDEX-MATCH",
  quizzes: lookupQuizzes,
  concepts: [
    {
      id: "lookup-vlookup",
      title: "VLOOKUP 구조와 한계",
      kind: "grid",
      why: "왼쪽 키로 오른쪽 값을 찾는다. 열 삽입에 깨진다.",
      syntax: "VLOOKUP(lookup, table, col_index, 0)",
      trap: "네 번째 인수는 반드시 0(정확 일치). TRUE는 정렬된 근사다.",
      ib: "레거시 파일에 남아 있다. 새 모델은 INDEX-MATCH 또는 XLOOKUP.",
      labIds: ["lookup-vlookup"],
      quizIds: ["lookup-q1"],
    },
    {
      id: "lookup-xlookup",
      title: "XLOOKUP",
      kind: "grid",
      why: "방향 제한이 없고 if_not_found를 인수로 받는다.",
      syntax: "XLOOKUP(lookup, lookup_array, return_array, [if_not_found], 0)",
      trap: "match_mode 기본이 정확 일치다. 근사를 켜지 않는다.",
      ib: "신형 Excel 표준 조회.",
      labIds: ["lookup-xlookup", "lookup-xlookup-left", "lookup-xlookup-missing"],
      quizIds: ["lookup-q1", "lookup-q4", "lookup-q5", "lookup-q6", "lookup-q7", "lookup-q8"],
    },
    {
      id: "lookup-index",
      title: "INDEX(범위, 행, [열])",
      kind: "grid",
      why: "위치만 알면 값을 꺼낸다. MATCH와 짝이다.",
      syntax: "INDEX(array, row_num, [column_num])",
      trap: "행/열 번호는 1부터. 0이면 전체가 배열로 나온다.",
      ib: "2차원 실적 표에서 연도×항목.",
      labIds: ["lookup-index-match"],
      quizIds: ["lookup-q3"],
    },
    {
      id: "lookup-match",
      title: "MATCH(값, 범위, [유형])",
      kind: "grid",
      why: "값이 몇 번째인지 돌려 INDEX에 넘긴다.",
      syntax: "MATCH(lookup_value, lookup_array, 0)",
      trap: "세 번째 인수 0이 정확 일치. 1/-1은 근사.",
      ib: "헤더에서 연도를 찾을 때.",
      labIds: ["lookup-match"],
      quizIds: ["lookup-q2"],
    },
    {
      id: "lookup-index-match",
      title: "INDEX-MATCH 조합",
      kind: "grid",
      why: "조회 열이 왼쪽에 있어도 된다. 열 삽입에 안전하다.",
      syntax: "INDEX(return, MATCH(key, keys, 0))",
      trap: "두 범위의 높이가 다르면 엉뚱한 행.",
      ib: "티커→이름, 티커→배수.",
      labIds: ["lookup-index-match"],
      quizIds: ["lookup-q1"],
    },
    {
      id: "lookup-2d",
      title: "2차원: INDEX-MATCH-MATCH",
      kind: "grid",
      why: "행 키와 열 키를 동시에 찾는다.",
      syntax: "INDEX(grid, MATCH(row, row_headers, 0), MATCH(col, col_headers, 0))",
      trap: "헤더에 중복 연도가 있으면 첫 번째만 맞는다.",
      ib: "연도×세그먼트 매출 표.",
      labIds: ["lookup-2d"],
      quizIds: ["lookup-q3"],
    },
  ],
};

export const PHASE1: Phase = {
  phase: 1,
  title: "Excel 기초 체력",
  weeks: "1–2주차",
  desc: "마우스 없이 엑셀을 다루는 속도감 + 핵심 함수 12개",
  modules: [nav, basicFn, logic, lookup],
};
