import { writeFileSync } from "node:fs";
import { IB_ENG_LESSONS, IB_ENG_QUESTIONS, ibEngModuleSlug } from "../lib/quiz/ib-eng";

function sqlStr(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlArray(values: string[]): string {
  return `array[${values.map(sqlStr).join(", ")}]`;
}

const lessonRows = IB_ENG_LESSONS.map(
  (lesson) =>
    `  (${sqlStr(lesson.domain)}, ${sqlStr(lesson.title)}, ${sqlStr(lesson.content)}, ${sqlArray(lesson.keyTerms)})`,
).join(",\n");

const questionRows = IB_ENG_QUESTIONS.map(
  (q) =>
    `  (${sqlStr(q.domain)}, ${sqlStr(ibEngModuleSlug(q.id))}, ${sqlStr(q.hint)}, ${sqlStr(q.question)}, ${sqlArray([...q.choices])}, ${q.answer}, ${sqlStr(q.explanation)}, ${q.difficulty})`,
).join(",\n");

const sql = `-- Seed: IB Engineering quiz bank + domain lessons
-- Generated by scripts/gen-ib-eng-seed.ts. Do not edit by hand.
-- Re-run deletes ib_eng_* rows (attempts cascade). Hosted apply is operator-owned.

delete from quiz_questions where domain like 'ib_eng_%';
delete from quiz_domain_lessons where domain like 'ib_eng_%';

insert into quiz_domain_lessons (domain, title, content, key_terms) values
${lessonRows};

insert into quiz_questions (domain, module_slug, concept_hint, question, choices, answer_index, explanation, difficulty) values
${questionRows};
`;

writeFileSync("supabase/seed-ib-engineering.sql", sql);
console.log(`wrote supabase/seed-ib-engineering.sql (${IB_ENG_QUESTIONS.length} questions, ${IB_ENG_LESSONS.length} lessons)`);
